(()=>{
const data={
'american-whirlpool':{
name:'American Whirlpool',tag:'Experience the American Whirlpool Difference.',lede:'Purposeful hydrotherapy, efficient performance and serviceable construction — designed for people who want their hot tub to feel as good years from now as it does on day one.',chips:['Zone Therapy®','Northern Exposure®','Appliance Grade construction','Hot tubs & swim spas'],heroImage:'assets/hot-tubs/american-whirlpool/471.webp',heroLabel:'American Whirlpool 471',
visual:[
['Physician Designed Zone Therapy®','Strategically positioned jets target specific muscular trigger-point zones. American Whirlpool’s approach emphasizes correct jet size, pressure and placement rather than simply adding more jets.','assets/hot-tubs/american-whirlpool/481.webp','https://americanwhirlpool.com/physician-designed-zone-therapy/'],
['Northern Exposure®','A three-layer thermal barrier uses reflective material, recycled-fiber insulation and an exterior insulation layer to help retain equipment heat while keeping internal components accessible for service.','assets/hot-tubs/american-whirlpool/471.webp','https://americanwhirlpool.com/northern-exposure/'],
['Comfort Collar® & Performance Seating','Ergonomic seating, neck support and targeted neck-and-shoulder massage are designed to work together with buoyancy and jet positioning for a more supported soak.','assets/hot-tubs/american-whirlpool/881.webp','https://americanwhirlpool.com/physician-designed-zone-therapy/']],
series:[['100 & 200 Series','Approachable sizes and layouts for couples, smaller spaces and everyday soaking.'],['400 Series','A stronger emphasis on therapy features, seating variety and premium appointments.'],['800 Series','Premium hydrotherapy with more equipment, massage variety and flagship-level configurations.']],maax:true},
'vita-spas':{
name:'Vita Spas',tag:'Vitality for Life.',lede:'Vita Spa combines relaxation, recovery and everyday usability with a wide range of massage experiences and feature levels for different households and wellness routines.',chips:['100–700 Series','Northern Exposure®','Clean water systems','Hot tubs & swim spas'],heroImage:'assets/hot-tubs/vita-spa/rendezvous.webp',heroLabel:'Vita Spa Rendezvous',
visual:[
['Northern Exposure® Insulation','Copper IR reflector, BlueMAAX® recycled-fiber insulation and 3M Thinsulate™ form a three-layer system designed to keep heat in while allowing service access to internal components.','assets/hot-tubs/vita-spa/cabaret.webp','https://vitaspa.com/innovations/northern-exposure/'],
['Clean, Clear Water','Vita offers water-care technologies designed to simplify routine ownership and reduce the work between you and a clean, inviting soak.','assets/hot-tubs/vita-spa/prestige.webp','https://vitaspa.com/innovations/how-we-innovate/'],
['Controls & Everyday Experience','From straightforward tactile controls to SmartTouch2 on select collections, Vita focuses on making temperature, filtration, lighting and massage settings easy to manage.','assets/hot-tubs/vita-spa/rendezvous.webp','https://vitaspa.com/features/controls/']],
series:[['100 & 300 Series','Accessible Vita Spa ownership with practical layouts and essential comfort features.'],['500 Series','A step up in controls, massage options, construction features and overall experience.'],['700 Series','Vita’s premium hot-tub collection with SmartTouch2, enhanced therapy and elevated appointments.']],maax:true},
'cal-spas':{
name:'Cal Spas',tag:'Hydrotherapy to Heal Minds and Bodies™.',lede:'A deep American-made lineup with everything from approachable plug-and-play models to advanced hydrotherapy, premium controls, swim spas and specialty wellness products.',chips:['Made since 1978','Made in the USA','Patio through Platinum','Hot tubs & swim spas'],heroImage:'assets/hot-tubs/cal-spas/arcata.webp',heroLabel:'Cal Spas Arcata',
visual:[
['Ergonomic Seating & Hydrotherapy','Contoured seating and strategically positioned jets are designed to support the body and target common areas of tension. Higher-feature models add technologies such as Velocity™ and Vector X™ jets and Adjustable Therapy System™ seating.','assets/hot-tubs/cal-spas/baja.webp','https://www.calspas.com/Why-Cal-Spas'],
['Insulation Built for Four Seasons','Cal Spas offers multiple insulation approaches, including Thermo-Shield™ and available full-foam systems designed to reduce heat loss and help maintain water temperature through changing seasons.','assets/hot-tubs/cal-spas/atlantic-x.webp','https://www.calspas.com/Why-Cal-Spas'],
['Heating & Everyday Performance','A titanium heater and efficiency-focused equipment package support regular year-round use, while the deeper collections add more pumps, filtration and therapy capability.','assets/hot-tubs/cal-spas/arcata.webp','https://www.calspas.com/Why-Cal-Spas'],
['Covers, Controls & Smart Options','From insulated spa covers to touch controls, lighting, audio and Cal Connect™ Wi‑Fi on compatible models, Cal offers a long menu of ways to tailor the spa.','assets/hot-tubs/cal-spas/malibu.webp','https://www.calspas.com/Why-Cal-Spas']],
series:[['Patio & Patio Plus','A strong starting point for shoppers focused on value, comfort and straightforward hydrotherapy.'],['Escape & Escape X','More therapy, more equipment and more ways to personalize the experience.'],['Platinum & Deck','Higher-feature collections for shoppers who want premium hydrotherapy, larger formats and elevated appointments.']],
collections:[['Patio™','Approachable everyday hot tubs.'],['Patio Plus™','More features while staying value-focused.'],['Escape™','A step up in hydrotherapy and equipment.'],['Escape X™','Higher-performance therapy and appointments.'],['Platinum™','Premium Cal Spas hot tubs.'],['Deck™','Oversized spas for entertaining and integrated spaces.'],['Swim™','Exercise, family fun and hydrotherapy.'],['Cold Plunge™','Cold-water wellness options.']],external:'https://calspasmonroeville.com/'},
'aquasolus':{name:'AquaSolus',tag:'The Ultimate Wellness Experience.',lede:'AquaSolus blends sculpted comfort, refined styling and wellness-led hydrotherapy with a lineup that is intentionally easy to understand.',chips:['Series One','Series Two','EcoPure water care','AquaSounds Bluetooth'],visual:[['Sculpted Comfort & Hydrotherapy','AquaSolus emphasizes the curvature of the acrylic, body-supporting seat shapes and carefully positioned hydrotherapy jets so the spa feels designed around the person using it.','assets/aquasolus-comfort.svg','https://aquasolus.com/us/about-aquasolus/'],['EcoPure Water Care','The EcoPure system is designed to simplify water management and support clear, inviting water while reducing dependence on heavy chemical use.','assets/aquasolus-watercare.svg','https://aquasolus.com/us/brand-features/'],['AquaSounds Included','AquaSounds Bluetooth audio is positioned as a standard premium feature across AquaSolus hot tubs, adding music and sound without turning it into an upgrade decision.','assets/aquasolus-audio.svg','https://aquasolus.com/us/brand-features/']],series:[['Series One','Brook, Zephyr and Cove focus on approachable luxury.'],['Series Two','Calma, Aspen and Eden step up hydrotherapy, equipment and premium features.'],['Series Three','Cascade, Serenity, Solstice and Zenith bring the premium end of the AquaSolus lineup.']]},
'eco-spas':{name:'Eco Spas',tag:'Simple. Affordable. Durable.',lede:'Eco Spas take a refreshingly practical approach to hot-tub ownership: rugged unibody construction, an integrated hard-cover system, flexible electrical options and straightforward hydrotherapy without unnecessary complexity.',chips:['Original Hard Cover Spa®','Rotationally molded','110V / 220V options','E1–E6 models'],features:[['The Original Hard Cover Spa®','A rigid slide-to-open hard-cover design protects the water and creates a tight insulating barrier when the spa is closed.'],['Unibody construction','Rotationally molded construction avoids many of the peeling, rotting and rust concerns associated with traditional exterior materials.'],['Flexible power','Applicable models can balance 110V convenience with 220V performance configurations.']],series:[['E1 & E2','Compact choices for smaller spaces and couples.'],['E3, E4 & E5','Flexible midsize layouts spanning intimate lounge seating through four-person configurations.'],['E6','The roomier six-person option for families and social soaking.']]},
'innova-spas':{name:'Innova Spas',tag:'Comfort within reach of all.',lede:'Portable spas designed around different lifestyles, from open social seating to stronger massage and relaxed lounge-style experiences.',chips:['Portable spas','110V convenience','Lifestyle-based models','Nearly 20 years'],features:[['Lifestyle choices','Models built around simplicity, togetherness, massage or laid-back relaxation.'],['Portable construction','Freestanding spas that are practical to place and straightforward to own.'],['Comfort and positioning','Seating position and massage style guide how each spa feels day to day.']],series:[['Stream','A social layout with roomy seating and multiple massage positions.'],['Fantom','Contemporary styling with stadium seating plus a full-body lounger.'],['Storm','A compact family-oriented spa with strategically positioned stainless-steel jets.']]}}
};
const key=new URLSearchParams(location.search).get('brand')||'american-whirlpool';
const x=data[key]||data['american-whirlpool'];
document.title=`${x.name} | Hot Tub Factory Outlet`;
const fallback=(name)=>`<div class="feature-fallback"><span class="eyebrow">${name}</span><strong>Premium hot tubs at HTFO</strong><small>Image temporarily unavailable</small></div>`;
const image=(src,alt)=>`<img src="${src}" alt="${alt}" loading="lazy" onerror="this.outerHTML=${JSON.stringify('@@FALLBACK@@').replace('@@FALLBACK@@','\`+fallback(alt)+\`')}">`;
function safeImage(src,alt){return `<img src="${src}" alt="${alt}" loading="lazy" onerror="this.style.display='none';this.parentElement.classList.add('image-error');this.parentElement.insertAdjacentHTML('beforeend',decodeURIComponent('${encodeURIComponent('<div class="feature-fallback"><span class="eyebrow">HTFO</span><strong>Premium hot tubs at HTFO</strong><small>Image temporarily unavailable</small></div>')}'))">`}
const heroVisual=x.heroImage?`<div class="brand-hero-photo">${safeImage(x.heroImage,x.heroLabel||x.name)}<div class="brand-hero-badge"><span>${x.name}</span><b>See it at HTFO</b></div></div>`:`<div class="hero-card"><h3>Why shoppers consider ${x.name}</h3><p>${x.lede}</p></div>`;
const visual=x.visual?`<section class="section"><div class="head"><span class="eyebrow">Signature features</span><h2>See what makes ${x.name} different.</h2><p>${key==='cal-spas'?'Cal offers a lot of options. These are the differences worth understanding before you start comparing individual model numbers.':'We’ve paired the feature story with actual spas from the line so the page feels like a showroom, not a technical brochure.'}</p></div><div class="visual-features">${x.visual.map((f,i)=>`<article class="visual-feature"><div class="feature-art product-photo">${safeImage(f[2],f[0])}<div class="photo-caption">Representative ${x.name} model · feature availability varies by series</div></div><div class="feature-copy"><span class="eyebrow">${String(i+1).padStart(2,'0')} · ${x.name}</span><h3>${f[0]}</h3><p>${f[1]}</p>${f[3]?`<a href="${f[3]}" target="_blank" rel="noopener">Learn more from ${x.name} →</a>`:''}</div></article>`).join('')}</div></section>`:`<section class="section"><div class="head"><span class="eyebrow">Brand story</span><h2>What ${x.name} emphasizes.</h2></div><div class="feature-grid">${x.features.map(f=>`<article class="feature"><h3>${f[0]}</h3><p>${f[1]}</p></article>`).join('')}</div></section>`;
const collections=x.collections?`<section class="section cal-collections"><div class="head"><span class="eyebrow">Cal Spas collections</span><h2>A lot of choices — made easier.</h2><p>Start with the family that fits your goals. For every model, specification and option, the dedicated Cal Spas Monroeville site has the complete catalog.</p></div><div class="collection-grid">${x.collections.map(c=>`<article class="collection-card"><h3>${c[0]}</h3><p>${c[1]}</p></article>`).join('')}</div><div class="collection-actions"><a class="btn primary" href="tel:4123260361">Talk to HTFO · 412-326-0361</a><a class="btn secondary external" href="${x.external}" target="_blank" rel="noopener">Explore Complete Cal Spas Collection ↗</a></div></section>`:'';
const heritage=x.maax?`<section class="section"><div class="heritage"><div class="mark">MAAX</div><div><span class="eyebrow" style="color:#78c8ec">Shared manufacturing heritage</span><h3>Built by MAAX Spas</h3><p>American Whirlpool and Vita Spa share MAAX Spas manufacturing heritage, with a long-running emphasis on product innovation, serviceability and hot-water wellness.</p></div></div></section>`:'';
const heroExtra=x.external?`<a class="text-link" href="${x.external}" target="_blank" rel="noopener">Explore the dedicated Cal Spas Monroeville site ↗</a>`:'';
document.querySelector('#app').innerHTML=`<section class="hero ${key==='cal-spas'?'cal-hero':''}"><div><span class="eyebrow">Hot Tub Factory Outlet · Pittsburgh</span><h1>${x.name}</h1><p class="tagline">${x.tag}</p><p class="lede">${x.lede}</p><div class="actions" style="margin-top:28px"><a class="btn primary" href="index.html#specials">See This Week's Special</a><a class="btn secondary" href="hot-tubs.html">Shop ${x.name} Models</a></div>${heroExtra}</div>${heroVisual}</section><section class="section alt"><div class="head"><span class="eyebrow">At a glance</span><h2>Why ${x.name} belongs on your shortlist.</h2></div><div class="chips">${x.chips.map(c=>`<span class="chip">${c}</span>`).join('')}</div></section>${visual}<section class="section alt"><div class="head"><span class="eyebrow">Where to start</span><h2>Choose the part of the lineup that fits you.</h2></div><div class="series">${x.series.map(s=>`<article class="series-card"><small>${x.name}</small><h3>${s[0]}</h3><p>${s[1]}</p></article>`).join('')}</div></section>${collections}${heritage}<section class="cta-band"><h2>Ready to sit in one?</h2><div class="actions"><a class="btn primary" href="hot-tubs.html">Shop Hot Tubs</a><a class="btn secondary" href="spa-quiz.html">Let Bubbles Help Me Choose</a></div></section>`;
})();