(()=>{const data=window.HTFO_FILTERS||[],$=s=>document.querySelector(s),esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const aliases={'vita':['vita spa','vita'],'vita spa':['vita spa','vita'],'maax':['maax spas','maax'],'maax spas':['maax spas','maax'],'cal spas':['cal spas','cal spa'],'jacuzzi':['jacuzzi'],'master spas':['master spas'],'artesian':['artesian'],'artesian spas':['artesian'],'waterway':['waterway'],'la spas':['la spas','advanced / la spas','advanced/la spas'],'bullfrog':['bullfrog'],'sundance':['sundance'],'hot spring':['watkins','hot spring']};
function refs(x){return [x.oemPart,x.pleatco,x.unicel,x.filbur,x.upc,...(x.crossRefs||[])].filter(Boolean)}
function hay(x){return [x.id,x.oncore,x.description,x.oem,x.productRange,x.sqft,...(x.shopBrands||[]),...refs(x)].filter(Boolean).join(' ').toLowerCase()}
function card(x){const cr=refs(x);const refText=cr.length?`<br><strong>Cross references:</strong> ${esc(cr.join(' · '))}`:'';const oem=x.oem?`<br><strong>OEM / manufacturer:</strong> ${esc(x.oem)}`:'';const media=x.productRange?`<br><strong>Media:</strong> ${esc(x.productRange)}${x.sqft&&x.sqft!=='NA'?` · ${esc(x.sqft)} sq ft`:''}`:'';return `<article class="resultcard"><div><h3>${esc(x.oncore||x.id)} Replacement Filter</h3><div class="meta">${x.description?`${esc(x.description)}<br>`:''}<strong>Outside diameter:</strong> ${esc(x.od)}&quot; · <strong>Length:</strong> ${esc(x.length)}&quot;<br><strong>Top:</strong> ${esc(x.top)} · <strong>Bottom:</strong> ${esc(x.bottom)}${oem}${media}${refText}</div><div class="status">2026 OnCore catalog match</div></div><div><div class="price">${x.price==null?'Price coming soon':`$${Number(x.price).toFixed(2)}`}</div><div class="pending">Call or visit HTFO for price and ordering. OnCore-branded filters are finder/display only on the website.</div></div></article>`}
function render(el,rows,msg){el.innerHTML=rows.length?`<div class="count">${rows.length} possible match${rows.length===1?'':'es'}</div>${rows.slice(0,75).map(card).join('')}`:`<div class="empty">${esc(msg)}</div>`}
function qTerms(q){const k=String(q||'').trim().toLowerCase();return aliases[k]||[k]}
function manufacturerRows(q){const terms=qTerms(q).filter(Boolean);if(!terms.length)return data;return data.filter(x=>terms.some(t=>hay(x).includes(t)))}
function search(){const brand=$('#manufacturer').value.trim(),part=$('#partSearch').value.trim().toLowerCase();let rows=manufacturerRows(brand);if(part)rows=rows.filter(x=>hay(x).includes(part));render($('#catalogResults'),rows,'No 2026 catalog match found. Try the manufacturer only, an OnCore/OEM/Pleatco/Unicel/Filbur number, or use measurements below.')}
$('#searchCatalog').addEventListener('click',search);['manufacturer','partSearch'].forEach(id=>$('#'+id).addEventListener('keydown',e=>{if(e.key==='Enter'){e.preventDefault();search()}}));document.querySelectorAll('[data-q]').forEach(b=>b.addEventListener('click',()=>{$('#manufacturer').value=b.dataset.q;$('#partSearch').value='';search()}));
function mixedNumber(v){return String(v).replace(/[“”"]/g,'').split(' ').reduce((n,p)=>{if(p.includes('/')){const[a,b]=p.split('/').map(Number);return n+(b?a/b:0)}return n+(Number(p)||0)},0)}
function vals(k,rows=data){return [...new Set(rows.map(x=>x[k]).filter(Boolean))].sort((a,b)=>{const an=mixedNumber(a),bn=mixedNumber(b);return Number.isFinite(an)&&Number.isFinite(bn)&&an!==bn?an-bn:String(a).localeCompare(String(b))})}
function fill(sel,k,label){sel.innerHTML=`<option value="">${label}</option>`;vals(k).forEach(v=>sel.insertAdjacentHTML('beforeend',`<option value="${esc(v)}">${esc(v)}${k==='od'||k==='length'?'&quot;':''}</option>`))}
fill($('#od'),'od','Any O.D.');fill($('#length'),'length','Any length');fill($('#top'),'top','Any top');fill($('#bottom'),'bottom','Any bottom');
$('#findFilter').addEventListener('click',()=>{const od=$('#od').value,len=$('#length').value,top=$('#top').value,bottom=$('#bottom').value,brand=$('#manufacturer').value.trim(),part=$('#partSearch').value.trim().toLowerCase();if(!od&&!len&&!top&&!bottom&&!brand&&!part){render($('#sizeResults'),[],'Choose at least one measurement, manufacturer, or part number.');return}let rows=manufacturerRows(brand);if(part)rows=rows.filter(x=>hay(x).includes(part));if(od)rows=rows.filter(x=>x.od===od);if(len)rows=rows.filter(x=>x.length===len);if(top)rows=rows.filter(x=>x.top===top);if(bottom)rows=rows.filter(x=>x.bottom===bottom);render($('#sizeResults'),rows,'No exact 2026 catalog match for that combination. Remove one criterion or bring the old cartridge to HTFO for identification.');});})();