window.HTFO_FILTERS=[
{id:'OC-210A',shopBrands:[],oncore:'OC-210A',description:'Spa Fill (Sediment) Cartridge',od:'2 3/4',length:'10',top:'Closed',bottom:'3/4" FGH',stock:true,price:null},
{id:'OC-404C',shopBrands:[],oncore:'OC-404C',description:'Threaded Top Load Filter',od:'4',length:'4',top:'Handle',bottom:'1 1/2" SAE',stock:true,price:null},
{id:'OC-404B',shopBrands:[],oncore:'OC-404B',description:'Waterway Skim Filter 10',od:'4 1/4',length:'4',top:'2 1/16" Open',bottom:'2 1/16" Open',stock:true,price:null},
{id:'OC-408D',shopBrands:[],oncore:'OC-408D',description:'Dream Maker Spas',od:'4 3/4',length:'8 1/8',top:'Handle',bottom:'1 1/2" MPT',stock:true,price:null},
{id:'OC-408DM',shopBrands:[],oncore:'OC-408DM',description:'Dream Maker Spas - Antimicrobial',od:'4 3/4',length:'8 1/8',top:'Handle',bottom:'1 1/2" MPT',stock:false,price:null},
{id:'OC-405A',shopBrands:[],oncore:'OC-405A',description:'Saratoga Spas',od:'4 5/8',length:'5 15/16',top:'Handle',bottom:'1 1/2" MPT',stock:false,price:null},
{id:'OC-406C',shopBrands:[],oncore:'OC-406C',description:'Top Load Filter',od:'4 5/8',length:'6 3/4',top:'Handle',bottom:'1 1/2" MPT',stock:true,price:null},
{id:'OC-408N',shopBrands:[],oncore:'OC-408N',description:'Pageant Spa Top Load',od:'4 5/8',length:'8',top:'Handle',bottom:'1 1/2" MPT',stock:false,price:null},
{id:'OC-408P',shopBrands:[],oncore:'OC-408P',description:'Futura Spa (Strong Industries)',od:'4 5/8',length:'8',top:'Handle',bottom:'1 1/2" SAE',stock:true,price:null},
{id:'OC-408Q',shopBrands:[],oncore:'OC-408Q',description:'20 SF Filter',od:'4 5/8',length:'8 1/16',top:'Handle',bottom:'2" MPT',stock:false,price:null},
{id:'OC-409A',shopBrands:[],oncore:'OC-409A',description:'After Hours / Nemco Spas Top Load',od:'4 5/8',length:'9 3/4',top:'Handle',bottom:'1 1/2" MPT',stock:true,price:null},
{id:'OC-411N',shopBrands:[],oncore:'OC-411N',description:'Saratoga Spas Circulation Pump',od:'4 5/8',length:'11 3/8',top:'Handle',bottom:'1 1/2" MPT',stock:true,price:null},
{id:'OC-411J',shopBrands:[],oncore:'OC-411J',description:'Advanced / LA Spas Top Load',od:'4 5/8',length:'11 7/8',top:'Handle',bottom:'1 1/2" MPT',stock:false,price:null},
{id:'OC-414B',shopBrands:[],oncore:'OC-414B',description:'Advanced / LA / Nemco Spas',od:'4 5/8',length:'14 3/4',top:'Handle',bottom:'1 1/2" MPT',stock:false,price:null},
{id:'OC-415A',shopBrands:[],oncore:'OC-415A',description:'Hot Spring Spas (Watkins) Top Load',od:'4 5/8',length:'15',top:'Handle',bottom:'1 1/2" MPT',stock:false,price:null},
{id:'OC-415B',shopBrands:[],oncore:'OC-415B',description:'Saratoga Spas Top Load',od:'4 5/8',length:'15 1/4',top:'Handle',bottom:'1 1/2" MPT',stock:false,price:null},
{id:'OC-508E',shopBrands:[],oncore:'OC-508E',description:'25 SF Filter',od:'5',length:'8 1/2',top:'Handle',bottom:'1 1/2" Female SAE',stock:false,price:null},
{id:'OC-510C',shopBrands:[],oncore:'OC-510C',description:'Jacuzzi Whirlpool 50 Front Load',od:'5 11/16',length:'10 3/8',top:'Loop with String Handle',bottom:'2 1/8" Open',stock:false,price:null},
{id:'OC-510D',shopBrands:[],oncore:'OC-510D',description:'Jacuzzi Aero / Caressa',od:'5 11/16',length:'10 3/8',top:'Loop with String Handle',bottom:'2 1/8" Open',stock:false,price:null},
{id:'OC-504A',shopBrands:[],oncore:'OC-504A',description:'Dynamic Series IV / Waterway',od:'5',length:'4 5/8',top:'2 1/8" Open',bottom:'2 3/16" Open',stock:false,price:null},
{id:'OC-506B',shopBrands:[],oncore:'OC-506B',description:'Dynamic Series IV / Waterway',od:'5',length:'6 5/8',top:'2 1/8" Open',bottom:'2 1/8" Open',stock:true,price:null},
{id:'OC-506C',shopBrands:[],oncore:'OC-506C',description:'Freeflow Lagas / TLX / RLX',od:'5',length:'6 5/8',top:'Closed',bottom:'1 1/2" MPT',stock:false,price:null},
{id:'OC-506D',shopBrands:[],oncore:'OC-506D',description:'Freeflow Lagas / CLX',od:'5',length:'6 5/8',top:'2 1/8" Open',bottom:'1 1/2" MPT',stock:false,price:null},
{id:'OC-509D',shopBrands:[],oncore:'OC-509D',description:'Dynamic Series IV / Waterway 35 In-Line',od:'5',length:'9 1/4',top:'2 1/8" Open',bottom:'2 1/8" Open',stock:true,price:null},
{id:'OC-509DM',shopBrands:[],oncore:'OC-509DM',description:'Dynamic Series IV / Waterway 35 In-Line - Antimicrobial',od:'5',length:'9 1/4',top:'2 1/8" Open',bottom:'2 1/8" Open',stock:true,price:null},
{id:'OC-509N',shopBrands:[],oncore:'OC-509N',description:'Waterway Teleweir 35',od:'5',length:'9 1/4',top:'Handle',bottom:'1 1/2" Female SAE',stock:true,price:null},
{id:'OC-509NM',shopBrands:[],oncore:'OC-509NM',description:'Waterway Teleweir 35 - Antimicrobial',od:'5',length:'9 1/4',top:'Handle',bottom:'1 1/2" Female SAE',stock:false,price:null},
{id:'OC-510J',shopBrands:[],oncore:'OC-510J',description:'Santana 25 Open Top',od:'5',length:'10 1/16',top:'2 1/8" Open',bottom:'2 1/8" Open',stock:false,price:null},
{id:'OC-511H',shopBrands:[],oncore:'OC-511H',description:'Waterway 40 In-Line',od:'5',length:'11 5/16',top:'2 1/8" Open',bottom:'2 1/8" Open',stock:false,price:null},
{id:'OC-513P',shopBrands:[],oncore:'OC-513P',description:'Waterway Teleweir 50',od:'5',length:'13 3/16',top:'Handle',bottom:'1 1/2" Female SAE',stock:true,price:null},
{id:'OC-513PM',shopBrands:[],oncore:'OC-513PM',description:'Waterway Teleweir 50 - Antimicrobial',od:'5',length:'13 3/16',top:'Handle',bottom:'1 1/2" Female SAE',stock:false,price:null},
{id:'OC-513B',shopBrands:[],oncore:'OC-513B',description:'Jacuzzi CFR/CFT 25',od:'5',length:'13 5/16',top:'2 3/8" Open',bottom:'2 3/8" Open',stock:true,price:null},
{id:'OC-513C',shopBrands:[],oncore:'OC-513C',description:'Jacuzzi CFR/CFT 37',od:'5',length:'13 5/16',top:'2 3/8" Open',bottom:'2 3/8" Open',stock:false,price:null},
{id:'OC-513D',shopBrands:[],oncore:'OC-513D',description:'Jacuzzi CFR/CFT 15',od:'5',length:'13 5/16',top:'2 3/8" Open',bottom:'2 3/8" Open',stock:false,price:null},
{id:'OC-513E',shopBrands:[],oncore:'OC-513E',description:'Dynamic Series / Waterway',od:'5',length:'13 5/16',top:'2 1/8" Open',bottom:'2 1/8" Open',stock:true,price:null},
{id:'OC-513G',shopBrands:[],oncore:'OC-513G',description:'Dynamic Series / Waterway / CMP',od:'5',length:'13 5/16',top:'2 1/8" Open',bottom:'2 1/8" Open',stock:true,price:null},
{id:'OC-513GM',shopBrands:[],oncore:'OC-513GM',description:'Dynamic Series / Waterway / CMP - Antimicrobial',od:'5',length:'13 5/16',top:'2 1/8" Open',bottom:'2 1/8" Open',stock:true,price:null},
{id:'OC-513J',shopBrands:[],oncore:'OC-513J',description:'Dynamic / Waterway / Morgan / Leisure Bay / CMP',od:'5',length:'13 5/16',top:'2 1/8" Open',bottom:'2 1/8" Open',stock:false,price:null},
{id:'OC-513K',shopBrands:[],oncore:'OC-513K',description:'Dynamic Series / Waterway / CMP 50',od:'5',length:'13 5/16',top:'2 1/8" Open',bottom:'2 1/8" Open',stock:true,price:null},
{id:'OC-513KM',shopBrands:[],oncore:'OC-513KM',description:'Dynamic Series / Waterway / CMP 50 - Antimicrobial',od:'5',length:'13 5/16',top:'2 1/8" Open',bottom:'2 1/8" Open',stock:true,price:null},
{id:'OC-514C',shopBrands:['Cal Spas'],oncore:'OC-514C',description:'Sonfarrel 50 / Cal Spas / Martec / Advantage',od:'5',length:'14 7/8',top:'2 1/8" Open',bottom:'2 1/8" Open',stock:false,price:null},
{id:'OC-514D',shopBrands:[],oncore:'OC-514D',description:'Sonfarrel 45',od:'5',length:'14 7/8',top:'2 1/8" Open',bottom:'2 1/8" Open',stock:false,price:null},
{id:'OC-517A',shopBrands:[],oncore:'OC-517A',description:'Advantage Electric 50',od:'5',length:'17 3/8',top:'2 1/8" Open',bottom:'2 1/8" Open',stock:false,price:null},
{id:'OC-517D',shopBrands:[],oncore:'OC-517D',description:'Santana 45',od:'5',length:'17 5/8',top:'2 1/8" Open',bottom:'2 1/8" Open',stock:false,price:null},
{id:'OC-520A',shopBrands:[],oncore:'OC-520A',description:'Dynamic Series V / II / III / CMP',od:'5',length:'20 1/8',top:'2 1/8" Open',bottom:'2 1/8" Open',stock:true,price:null},
{id:'OC-520AM',shopBrands:[],oncore:'OC-520AM',description:'Dynamic Series V / II / III / CMP - Antimicrobial',od:'5',length:'20 1/8',top:'2 1/8" Open',bottom:'2 1/8" Open',stock:true,price:null},
{id:'OC-523A',shopBrands:[],oncore:'OC-523A',description:'Waterway In-Line 75',od:'5',length:'23 5/8',top:'2 1/8" Open',bottom:'2 1/8" Open',stock:false,price:null},
{id:'OC-523B',shopBrands:['Cal Spas'],oncore:'OC-523B',description:'Waterway 100 / Cal Spas',od:'5',length:'23 5/8',top:'2 1/8" Open',bottom:'2 1/8" Open',stock:false,price:null},
{id:'OC-526A',shopBrands:[],oncore:'OC-526A',description:'Dynamic Series II / III / V',od:'5',length:'26 1/2',top:'2 1/8" Open',bottom:'2 1/8" Open',stock:false,price:null},
{id:'OC-509A',shopBrands:[],oncore:'OC-509A',description:'Freeflow 2013-current',od:'5 1/4',length:'9 3/8',top:'Closed - String Handle',bottom:'1 1/2" MPT',stock:true,price:null},
{id:'OC-509AM',shopBrands:[],oncore:'OC-509AM',description:'Freeflow 2013-current - Antimicrobial',od:'5 1/4',length:'9 3/8',top:'Closed - String Handle',bottom:'1 1/2" MPT',stock:false,price:null},
{id:'OC-510L',shopBrands:[],oncore:'OC-510L',description:'Jacuzzi Hermosa / Redondo / Del Sol',od:'5 3/16',length:'10 5/8',top:'Handle',bottom:'2" MPT',stock:true,price:null},
{id:'OC-512C',shopBrands:[],oncore:'OC-512C',description:'Pacific Marquis Spas 50',od:'5 3/16',length:'12 1/4',top:'Handle',bottom:'2" MPT',stock:true,price:null},
{id:'OC-512CM',shopBrands:[],oncore:'OC-512CM',description:'Pacific Marquis Spas 50 - Antimicrobial',od:'5 3/16',length:'12 1/4',top:'Handle',bottom:'2" MPT',stock:false,price:null},
{id:'OC-512E',shopBrands:[],oncore:'OC-512E',description:'Pacific Marquis Spas 35',od:'5 3/16',length:'12 1/4',top:'Handle',bottom:'2" MPT',stock:true,price:null},
{id:'OC-512EM',shopBrands:[],oncore:'OC-512EM',description:'Pacific Marquis Spas 35 - Antimicrobial',od:'5 3/16',length:'12 1/4',top:'Handle',bottom:'2" MPT',stock:false,price:null},
{id:'OC-516A',shopBrands:['Cal Spas'],oncore:'OC-516A',description:'Cal Spa Victory 60',od:'5 3/16',length:'16',top:'Handle',bottom:'2" MPT',stock:false,price:null},
{id:'OC-516AM',shopBrands:['Cal Spas'],oncore:'OC-516AM',description:'Cal Spa Victory 60 - Antimicrobial',od:'5 3/16',length:'16',top:'Handle',bottom:'2" MPT',stock:true,price:null},
{id:'OC-508A',shopBrands:[],oncore:'OC-508A',description:'LA Spas replacement for bag filter',od:'5 3/8',length:'8 9/16',top:'Handle',bottom:'3" MPT',stock:true,price:null},
{id:'OC-508AM',shopBrands:[],oncore:'OC-508AM',description:'LA Spas replacement for bag filter - Antimicrobial',od:'5 3/8',length:'8 9/16',top:'Handle',bottom:'3" MPT',stock:false,price:null},
{id:'OC-521A',shopBrands:[],oncore:'OC-521A',description:'Coast Spas / Waterway Top Load 100',od:'5 3/8',length:'21 5/16',top:'2 1/8" Open',bottom:'2 1/8" Open',stock:false,price:null},
{id:'OC-530A',shopBrands:[],oncore:'OC-530A',description:'Coast Spas / Waterway Top Load 135',od:'5 3/8',length:'30 1/8',top:'2 1/8" Open',bottom:'2 1/8" Open',stock:false,price:null},
{id:'OC-510A',shopBrands:[],oncore:'OC-510A',description:'Freeflow Spas Legend',od:'5 5/16',length:'10',top:'2 1/8" Open',bottom:'1 1/2" MPT',stock:false,price:null},
{id:'OC-510E',shopBrands:[],oncore:'OC-510E',description:'Leisure Bay / Dynasty / Waterway / Rainbow',od:'5 5/16',length:'10 1/8',top:'2 1/8" Open',bottom:'2 1/8" Open',stock:false,price:null},
{id:'OC-510EM',shopBrands:[],oncore:'OC-510EM',description:'Leisure Bay / Dynasty / Waterway / Rainbow - Antimicrobial',od:'5 5/16',length:'10 1/8',top:'2 1/8" Open',bottom:'2 1/8" Open',stock:false,price:null},
{id:'OC-514A',shopBrands:[],oncore:'OC-514A',description:'Rainbow / Waterway / Leisure Bay / S2-G2 Spa 75',od:'5 5/16',length:'14 3/4',top:'2 1/8" Open',bottom:'2 1/8" Open',stock:true,price:null},
{id:'OC-514AM',shopBrands:[],oncore:'OC-514AM',description:'Rainbow / Waterway / Leisure Bay / S2-G2 Spa 75 - Antimicrobial',od:'5 5/16',length:'14 3/4',top:'2 1/8" Open',bottom:'2 1/8" Open',stock:true,price:null},
{id:'OC-517C',shopBrands:[],oncore:'OC-517C',description:'Rainbow / Waterway / Leisure Bay / S2-G2 Spa 100',od:'5 5/16',length:'17 3/4',top:'2 1/8" Open',bottom:'2 1/8" Open',stock:false,price:null},
{id:'OC-508F',shopBrands:['American Whirlpool','Vita Spa'],oncore:'OC-508F',description:'MAAX Spas of Canada 25 SF',od:'5 5/8',length:'8',top:'Handle',bottom:'1 1/2" MPT',stock:true,price:null},
{id:'OC-508B',shopBrands:['American Whirlpool','Vita Spa'],oncore:'OC-508B',description:'MAAX Spas of Canada 50 SF',od:'5 5/8',length:'8',top:'Handle',bottom:'1 1/2" MPT',stock:true,price:null},
{id:'OC-508BM',shopBrands:['American Whirlpool','Vita Spa'],oncore:'OC-508BM',description:'MAAX Spas of Canada 50 SF - Antimicrobial',od:'5 5/8',length:'8',top:'Handle',bottom:'1 1/2" MPT',stock:false,price:null},
{id:'OC-508C',shopBrands:['American Whirlpool','Vita Spa'],oncore:'OC-508C',description:'MAAX Spas of Canada 25 SF',od:'5 5/8',length:'8',top:'Handle',bottom:'1 1/2" MPT',stock:false,price:null},
{id:'OC-508D',shopBrands:['American Whirlpool','Vita Spa'],oncore:'OC-508D',description:'MAAX Spas of Canada 50 SF',od:'5 5/8',length:'8',top:'Handle',bottom:'1 1/2" SAE',stock:false,price:null},
{id:'OC-510K',shopBrands:[],oncore:'OC-510K',description:'Watkins Hot Spring Spas',od:'5 7/8',length:'10 3/8',top:'1 15/16" Open',bottom:'1 15/16" Open',stock:true,price:null},
{id:'OC-605A',shopBrands:[],oncore:'OC-605A',description:'Softub / Leisure Bay',od:'6',length:'5 1/2',top:'Handle',bottom:'1 1/2" MPT',stock:false,price:null},
{id:'OC-606A',shopBrands:[],oncore:'OC-606A',description:'American Spas / Artesian (Coleman)',od:'6',length:'6 1/2',top:'Handle',bottom:'1 1/2" MPT',stock:false,price:null},
{id:'OC-607B',shopBrands:[],oncore:'OC-607B',description:'New Artesian 6 inch Spa',od:'6',length:'7 5/8',top:'Handle',bottom:'2" MPT',stock:true,price:null},
{id:'OC-607BM',shopBrands:[],oncore:'OC-607BM',description:'New Artesian 6 inch Spa - Antimicrobial',od:'6',length:'7 5/8',top:'Handle',bottom:'2" MPT',stock:false,price:null},
{id:'OC-607D',shopBrands:[],oncore:'OC-607D',description:'Waterway Front Access Skimmer',od:'6',length:'7 5/8',top:'Handle',bottom:'1 1/2" SAE',stock:true,price:null},
{id:'OC-607DM',shopBrands:[],oncore:'OC-607DM',description:'Waterway Front Access Skimmer / Aber Hot Tubs - Antimicrobial',od:'6',length:'7 5/8',top:'Handle',bottom:'1 1/2" SAE',stock:false,price:null},
{id:'OC-607C',shopBrands:[],oncore:'OC-607C',description:'Top Load Sunrise Modification',od:'6',length:'7 7/8',top:'Handle',bottom:'1 1/2" MPT',stock:true,price:null},
{id:'OC-608E',shopBrands:[],oncore:'OC-608E',description:'Advanced / LA Spas / Aber Hottub',od:'6',length:'8 3/4',top:'Handle',bottom:'1 1/2" MPT',stock:true,price:null},
{id:'OC-609D',shopBrands:[],oncore:'OC-609D',description:'Master Spas Twilight',od:'6',length:'9 1/4',top:'Handle',bottom:'2" MPT',stock:true,price:null},
{id:'OC-609DM',shopBrands:[],oncore:'OC-609DM',description:'Master Spas Twilight - Antimicrobial',od:'6',length:'9 1/4',top:'Handle',bottom:'2" MPT',stock:false,price:null},
{id:'OC-609B',shopBrands:[],oncore:'OC-609B',description:'Four Seasons Spa',od:'6',length:'9 3/4',top:'Handle',bottom:'1 1/2" MPT',stock:false,price:null},
{id:'OC-609A',shopBrands:[],oncore:'OC-609A',description:'DFA Spas / Arizona Pacific',od:'6',length:'9 13/16',top:'Handle',bottom:'1 1/2" MPT',stock:false,price:null},
{id:'OC-611A',shopBrands:[],oncore:'OC-611A',description:'Master Spas / Freedom Spas',od:'6',length:'11 15/16',top:'Handle',bottom:'1 1/2" MPT',stock:false,price:null},
{id:'OC-613A',shopBrands:[],oncore:'OC-613A',description:'Advanced / LA Spas',od:'6',length:'13 3/16',top:'Handle',bottom:'1 1/2" MPT',stock:false,price:null},
{id:'OC-613B',shopBrands:[],oncore:'OC-613B',description:'Seven Seas Spas',od:'6',length:'13 3/8',top:'Handle',bottom:'1 1/2" MPT',stock:false,price:null},
{id:'OC-614A',shopBrands:[],oncore:'OC-614A',description:'Caribbean / Catalina / Jetta / Wild Water Spa',od:'6',length:'14 13/16',top:'Handle',bottom:'1 1/2" MPT',stock:false,price:null},
{id:'OC-614B',shopBrands:[],oncore:'OC-614B',description:'Advanced Spa 75',od:'6',length:'14 13/16',top:'Handle',bottom:'1 1/2" MPT',stock:false,price:null},
{id:'OC-608A',shopBrands:[],oncore:'OC-608A',description:'Master Spas outer cartridge',od:'6 1/2',length:'8',top:'4 1/16" Open',bottom:'4 1/16" Open',stock:true,price:null},
{id:'OC-608AM',shopBrands:[],oncore:'OC-608AM',description:'Master Spas outer cartridge - Antimicrobial',od:'6 1/2',length:'8',top:'4 1/16" Open',bottom:'4 1/16" Open',stock:false,price:null},
{id:'OC-707E',shopBrands:[],oncore:'OC-707E',description:'Artesian Spas 50',od:'6 3/4',length:'7 7/8',top:'Handle',bottom:'2" MPT',stock:true,price:null},
{id:'OC-607A',shopBrands:[],oncore:'OC-607A',description:'Artesian Spas 50',od:'6 3/4',length:'7 7/8',top:'Handle',bottom:'2" MPT',stock:true,price:null},
{id:'OC-614C',shopBrands:[],oncore:'OC-614C',description:'Watkins Hot Spring Spas 35',od:'6 3/8',length:'14',top:'1 15/16" Open',bottom:'1 15/16" Open',stock:true,price:null},
{id:'OC-614D',shopBrands:[],oncore:'OC-614D',description:'Watkins Hot Spring Spas 70',od:'6 3/8',length:'14',top:'1 15/16" Open',bottom:'1 15/16" Open',stock:true,price:null},
{id:'OC-615A',shopBrands:[],oncore:'OC-615A',description:'Jacuzzi Premium J-300 / J-400',od:'6 5/8',length:'15 1/2',top:'Open Top',bottom:'2" SAE',stock:true,price:null},
{id:'OC-615B',shopBrands:[],oncore:'OC-615B',description:'Jacuzzi Premium J-300 / J-400',od:'6 5/8',length:'15 1/2',top:'Handle',bottom:'2" SAE',stock:true,price:null},
{id:'OC-707D',shopBrands:[],oncore:'OC-707D',description:'Sunrise',od:'7',length:'7 7/8',top:'Handle',bottom:'1 1/2" MPT',stock:false,price:null},
{id:'OC-709H',shopBrands:['Vita Spa'],oncore:'OC-709H',description:'40 SF Vita Spa / Coleman Top Load',od:'7',length:'9 7/8',top:'Handle',bottom:'1 1/2" MPT',stock:false,price:null},
{id:'OC-710A',shopBrands:[],oncore:'OC-710A',description:'Caldera 50',od:'7',length:'10 3/4',top:'Swivel Handle',bottom:'2" Male Slip',stock:false,price:null},
{id:'OC-710B',shopBrands:[],oncore:'OC-710B',description:'Caldera 50 new style',od:'7',length:'10 3/4',top:'Swivel Handle',bottom:'2 11/16" Open',stock:false,price:null},
{id:'OC-710BM',shopBrands:[],oncore:'OC-710BM',description:'Caldera 50 new style - Antimicrobial',od:'7',length:'10 3/4',top:'Swivel Handle',bottom:'2 11/16" Open',stock:false,price:null},
{id:'OC-714C',shopBrands:[],oncore:'OC-714C',description:'Caldera 75',od:'7',length:'14 5/8',top:'Swivel Handle',bottom:'2" Male Slip',stock:false,price:null},
{id:'OC-714X',shopBrands:['Vita Spa'],oncore:'OC-714X',description:'Coleman / Vita Spa',od:'7',length:'14 13/16',top:'Handle',bottom:'1 1/2" MPT',stock:false,price:null},
{id:'OC-714D',shopBrands:[],oncore:'OC-714D',description:'Caldera 75 new style',od:'7',length:'14 7/8',top:'Swivel Handle',bottom:'2 11/16" Open',stock:false,price:null},
{id:'OC-709J',shopBrands:[],oncore:'OC-709J',description:'Waterco C-25',od:'7 1/4',length:'9 7/8',top:'3" Open',bottom:'3" Open',stock:false,price:null},
{id:'OC-710D',shopBrands:[],oncore:'OC-710D',description:'Dimension One 75 / @Home Hot Tubs',od:'7 1/4',length:'10 1/4',top:'Castle Top',bottom:'Special Lock Bottom',stock:true,price:null},
{id:'OC-714A',shopBrands:[],oncore:'OC-714A',description:'Advantage Electric 75',od:'7 1/4',length:'14 5/8',top:'2 15/16" Open',bottom:'2 15/16" Open',stock:false,price:null},
{id:'OC-721B',shopBrands:[],oncore:'OC-721B',description:'Advantage Electric 100',od:'7 1/4',length:'21 1/2',top:'3" Open',bottom:'3" Open',stock:true,price:null},
{id:'OC-728A',shopBrands:[],oncore:'OC-728A',description:'Advantage Electric 150',od:'7 1/4',length:'28 9/16',top:'3" Open',bottom:'3" Open',stock:false,price:null},
{id:'OC-707B',shopBrands:[],oncore:'OC-707B',description:'Master Spas Legacy / Freedom',od:'7 1/8',length:'7 3/16',top:'Handle',bottom:'2" MPT',stock:false,price:null},
{id:'OC-707A',shopBrands:[],oncore:'OC-707A',description:'Artesian Top Load Spa (Coleman)',od:'7 1/8',length:'7 9/16',top:'Handle',bottom:'2" MPT',stock:false,price:null},
{id:'OC-707AM',shopBrands:[],oncore:'OC-707AM',description:'Artesian Top Load Spa (Coleman) - Antimicrobial',od:'7 1/8',length:'7 9/16',top:'Handle',bottom:'2" MPT',stock:false,price:null},
{id:'OC-705A',shopBrands:[],oncore:'OC-705A',description:'Sundance Microclean Depth Filter',od:'7 3/4',length:'5',top:'4 3/4" Open',bottom:'4 3/4" Open',stock:true,price:null},
{id:'OC-805A',shopBrands:[],oncore:'OC-805A',description:'Bullfrog 35 2003-2012 short thread',od:'8',length:'5 3/4',top:'Handle',bottom:'2" Modified ACME',stock:true,price:null},
{id:'OC-805AM',shopBrands:[],oncore:'OC-805AM',description:'Bullfrog 35 2003-2012 short thread - Antimicrobial',od:'8',length:'5 3/4',top:'Handle',bottom:'2" Modified ACME',stock:true,price:null},
{id:'OC-805B',shopBrands:[],oncore:'OC-805B',description:'Bullfrog 35 2003-2012 long thread',od:'8',length:'5 3/4',top:'Handle',bottom:'2" Modified ACME',stock:true,price:null},
{id:'OC-806A',shopBrands:[],oncore:'OC-806A',description:'Master Spas EP new style',od:'8',length:'6 7/8',top:'4 1/16" Open',bottom:'4 1/16" Open',stock:true,price:null},
{id:'OC-806AM',shopBrands:[],oncore:'OC-806AM',description:'Master Spas EP new style - Antimicrobial',od:'8',length:'6 7/8',top:'4 1/16" Open',bottom:'4 1/16" Open',stock:false,price:null},
{id:'OC-809A',shopBrands:[],oncore:'OC-809A',description:'Coleman Spas 50',od:'8',length:'9',top:'2 1/8" Open',bottom:'2" Slip',stock:false,price:null},
{id:'OC-809B',shopBrands:[],oncore:'OC-809B',description:'Master Spas Top Load Cartridge',od:'8',length:'9 1/4',top:'Handle',bottom:'2" MPT',stock:false,price:null},
{id:'OC-813A',shopBrands:[],oncore:'OC-813A',description:'Coleman Spas 75',od:'8',length:'13 1/16',top:'2 1/8" Open',bottom:'2" Slip',stock:true,price:null},
{id:'OC-815B',shopBrands:[],oncore:'OC-815B',description:'Sundance Spas 95',od:'8',length:'15 1/2',top:'Handle',bottom:'2" MPT',stock:false,price:null},
{id:'OC-816A',shopBrands:[],oncore:'OC-816A',description:'Caldera 100',od:'8',length:'16 1/2',top:'Handle',bottom:'3 5/8" Open',stock:false,price:null},
{id:'OC-807A',shopBrands:['Vita Spa'],oncore:'OC-807A',description:'Vita Spa AB5-300',od:'8 1/2',length:'7 1/4',top:'Handle',bottom:'2" MPT',stock:false,price:null},
{id:'OC-807AM',shopBrands:['Vita Spa'],oncore:'OC-807AM',description:'Vita Spa AB5-300 - Antimicrobial',od:'8 1/2',length:'7 1/4',top:'Handle',bottom:'2" MPT',stock:false,price:null},
{id:'OC-810C',shopBrands:[],oncore:'OC-810C',description:'Watkins Hot Spring Spas upgrade',od:'8 1/2',length:'10 1/2',top:'3" Open',bottom:'3" Open',stock:true,price:null},
{id:'OC-814A',shopBrands:[],oncore:'OC-814A',description:'Sundance Microclean',od:'8 1/2',length:'14 5/8',top:'2" SAE Closed',bottom:'2 3/4" Beveled Edge',stock:true,price:null},
{id:'OC-819D',shopBrands:[],oncore:'OC-819D',description:'Sundance Double End 120',od:'8 1/2',length:'19',top:'2 3/16" Slip',bottom:'2 3/4" Beveled Edge',stock:false,price:null}
];
// Source: OnCore Filtration 2025 catalog, SPA replacement filters by measurement. Other-brand cross-reference part numbers are intentionally not stored here unless OnCore publishes them and HTFO later chooses to expose them.