(()=>{
const ENDPOINT='https://hot-tub-factory-outlet.onrender.com/lead';
const esc=s=>String(s||'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
function names(full){const p=String(full||'').trim().split(/\s+/).filter(Boolean);return{firstName:p.shift()||'',lastName:p.join(' ')}}
function ensure(){
 if(document.getElementById('htfoLeadModal'))return;
 const style=document.createElement('style');style.textContent=`.htfo-lead-overlay{position:fixed;inset:0;z-index:110000;background:#061b2bd9;display:none;padding:18px;align-items:center;justify-content:center}.htfo-lead-overlay.open{display:flex}.htfo-lead-card{width:min(560px,100%);background:#fff;border-radius:22px;box-shadow:0 24px 80px #0008;overflow:hidden}.htfo-lead-head{background:#082642;color:white;padding:22px 24px;position:relative}.htfo-lead-head h3{font-size:28px;margin:4px 42px 5px 0}.htfo-lead-head p{margin:0;color:#c9dce7;line-height:1.45}.htfo-lead-close{position:absolute;right:15px;top:14px;border:0;background:#ffffff18;color:white;width:34px;height:34px;border-radius:50%;font-size:22px;cursor:pointer}.htfo-lead-body{padding:22px 24px 25px}.htfo-lead-grid{display:grid;grid-template-columns:1fr 1fr;gap:12px}.htfo-lead-field{margin-bottom:12px}.htfo-lead-field.full{grid-column:1/-1}.htfo-lead-field label{display:block;font-weight:800;color:#082642;font-size:13px;margin-bottom:6px}.htfo-lead-field input,.htfo-lead-field textarea,.htfo-lead-field select{width:100%;box-sizing:border-box;border:1px solid #bfd0da;border-radius:10px;padding:12px;font:inherit}.htfo-lead-field textarea{min-height:88px;resize:vertical}.htfo-lead-submit{width:100%;border:0;background:#087fbd;color:#fff;border-radius:999px;padding:13px 18px;font-weight:900;cursor:pointer;font-size:15px}.htfo-lead-submit[disabled]{opacity:.6;cursor:wait}.htfo-lead-small{font-size:11px;color:#6a7e8c;line-height:1.45;margin:10px 0 0}.htfo-lead-status{display:none;margin:0 0 12px;padding:10px 12px;border-radius:9px;background:#eef8fc;color:#082642;font-size:13px}.htfo-lead-status.error{background:#fff0f0;color:#932626}.htfo-lead-success{text-align:center;padding:18px 5px}.htfo-lead-success h3{color:#082642;font-size:28px;margin:8px 0}.htfo-lead-success p{color:#536b80;line-height:1.55}@media(max-width:620px){.htfo-lead-overlay{padding:0}.htfo-lead-card{border-radius:0;min-height:100vh}.htfo-lead-grid{grid-template-columns:1fr}.htfo-lead-field.full{grid-column:auto}}`;document.head.appendChild(style);
 const el=document.createElement('div');el.id='htfoLeadModal';el.className='htfo-lead-overlay';el.innerHTML=`<div class="htfo-lead-card" role="dialog" aria-modal="true" aria-label="Request hot tub information"><div class="htfo-lead-head"><button class="htfo-lead-close" type="button" aria-label="Close">×</button><span style="font-size:12px;font-weight:900;letter-spacing:.1em;text-transform:uppercase;color:#7bd1f4">Hot Tub Factory Outlet</span><h3 data-title>Get pricing & availability</h3><p data-subtitle>Tell us what caught your eye and an HTFO specialist will follow up.</p></div><div class="htfo-lead-body"><div class="htfo-lead-status" data-status></div><form data-form><input type="hidden" name="source"><input type="hidden" name="brand"><input type="hidden" name="model"><div class="htfo-lead-grid"><div class="htfo-lead-field full"><label>Your name</label><input name="name" required autocomplete="name"></div><div class="htfo-lead-field"><label>Email</label><input name="email" type="email" required autocomplete="email"></div><div class="htfo-lead-field"><label>Mobile phone</label><input name="phone" type="tel" required autocomplete="tel"></div><div class="htfo-lead-field full"><label>What can we help with?</label><textarea name="message" placeholder="Price, availability, delivery timing, a specific model, financing... (optional)"></textarea></div></div><button class="htfo-lead-submit" type="submit">Send My Request →</button><p class="htfo-lead-small">By submitting, you agree that Hot Tub Factory Outlet may contact you about your request by phone, text or email.</p></form></div></div>`;document.body.appendChild(el);
 el.querySelector('.htfo-lead-close').addEventListener('click',close);el.addEventListener('click',e=>{if(e.target===el)close()});document.addEventListener('keydown',e=>{if(e.key==='Escape')close()});el.querySelector('[data-form]').addEventListener('submit',submit);
}
function open(opts={}){ensure();const el=document.getElementById('htfoLeadModal'),f=el.querySelector('[data-form]');f.reset();f.source.value=opts.source||'HTFO Website Quick Lead';f.brand.value=opts.brand||'';f.model.value=opts.model||'';el.querySelector('[data-title]').textContent=opts.title||'Get pricing & availability';el.querySelector('[data-subtitle]').textContent=opts.subtitle||(opts.model?`Ask us about the ${opts.brand||''} ${opts.model}.`:'Tell us what caught your eye and an HTFO specialist will follow up.');const st=el.querySelector('[data-status]');st.style.display='none';st.className='htfo-lead-status';el.classList.add('open');document.body.style.overflow='hidden';setTimeout(()=>f.name.focus(),60)}
function close(){const el=document.getElementById('htfoLeadModal');if(el)el.classList.remove('open');document.body.style.overflow=''}
async function submit(e){e.preventDefault();const f=e.currentTarget,btn=f.querySelector('button[type="submit"]'),st=f.closest('.htfo-lead-body').querySelector('[data-status]');const n=names(f.name.value);if(!n.firstName)return;const detail=[f.brand.value&&`Brand: ${f.brand.value}`,f.model.value&&`Model: ${f.model.value}`,f.message.value&&`Customer message: ${f.message.value}`,`Page: ${location.href}`].filter(Boolean).join('\n');const tags=['quick-lead'];if(f.brand.value)tags.push('model-interest');btn.disabled=true;btn.textContent='Sending…';st.style.display='none';try{const r=await fetch(ENDPOINT,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({firstName:n.firstName,lastName:n.lastName,email:f.email.value.trim(),phone:f.phone.value.trim(),source:f.source.value,tags,note:`WEBSITE QUICK LEAD\n\n${detail}`})});const j=await r.json().catch(()=>({}));if(!r.ok||!j.ok)throw new Error(j.error||'Unable to send request');f.parentElement.innerHTML=`<div class="htfo-lead-success"><div style="font-size:42px">✓</div><h3>You're in.</h3><p>We received your request and an HTFO specialist can follow up with the pricing, availability or product information you asked for.</p><button type="button" class="htfo-lead-submit" onclick="HTFOLead.close()">Done</button></div>`}catch(err){st.textContent=err.message||'Something went wrong. Please try again.';st.className='htfo-lead-status error';st.style.display='block';btn.disabled=false;btn.textContent='Send My Request →'}}
window.HTFOLead={open,close};
})();