const maaxBrands=new Set(['american-whirlpool','vita-spas']);
const manufacturerDetails={
'american-whirlpool':{headline:'Experience the American Whirlpool® Difference',body:'American Whirlpool describes itself as a quality leader in hot water products, pairing physician-designed Zone Therapy® seating with Northern Exposure® insulation and Appliance Grade® construction.',points:[['Zone Therapy®','Targeted seating and jet placement designed around specific areas of the body.'],['Northern Exposure®','A high-performance insulation approach designed for efficiency and quiet operation.'],['Appliance Grade®','Steel-frame construction and serviceability designed with long-term ownership in mind.']]},
'vita-spas':{headline:'Vitality for Life',body:'Vita Spa focuses on full-body rejuvenation, relaxation and recovery, with a long-standing emphasis on innovation, comfort and dependable ownership.',points:[['Wellness-focused seating','Different massage positions and seating styles give shoppers multiple ways to relax and recover.'],['Innovation and dependability','Vita presents its products around quality, comfort and long-term ownership.'],['A broad lineup','Compact, family-size and therapy-focused models make it easier to find a good personal fit.']]},
'cal-spas':{headline:'Hydrotherapy to Heal Minds and Bodies™',body:'Cal Spas offers one of the broadest hot tub lineups in the category, from Patio and Patio Plus through Escape, Escape X and Platinum collections.',points:[['Full-body hydrotherapy','Strategically placed jets and multiple seating layouts support relaxation and targeted massage.'],['Wide collection choice','Customers can compare different sizes, feature levels and seating configurations within one brand.'],['Made in the USA','Cal Spas highlights U.S. manufacturing using components sourced from around the world.']]},
'aquasolus':{headline:'The Ultimate Wellness Experience',body:'AquaSolus combines contemporary design, sculpted seating, hydrotherapy and wellness-focused features in a collection inspired by water, simplicity and balance.',points:[['Contemporary design','Sculpted forms, carefully positioned jets and modern styling create a distinct visual identity.'],['Hydrotherapy focus','Series One and Series Two provide different levels of relaxation and massage intensity.'],['Wellness-minded ownership','Purification, insulation and comfort features are designed around an easy-to-enjoy spa experience.']]},
'eco-spas':{headline:'Simple hot tub ownership',body:'Eco Spas gives customers a straightforward path to hot tub ownership with rotationally molded construction, easy operation and a strong emphasis on durability.',points:[['Simple setup','A focused product approach keeps ownership uncomplicated.'],['Rotationally molded construction','Durable one-piece construction is designed for practical, long-term use.'],['Everyday value','The emphasis stays on soaking, comfort and ownership rather than unnecessary complexity.']]},
'innova-spas':{headline:'Comfort within reach of all',body:'InnovaSpa builds a distinct family of portable spas for different lifestyles, from simple relaxation and family time to more intense massage.',points:[['Portable spa design','Rotationally molded construction makes placement and ownership more flexible.'],['Different lifestyles','Models are designed around relaxation, togetherness, massage intensity and seating preferences.'],['Nearly 20 years of experience','InnovaSpa highlights a long-running focus on comfort, design and customer feedback.']]}
};

function maaxHeritage(){return `<section class="heritage"><div><span class="eyebrow">MAAX Spas Heritage</span><h2>Part of a long-standing hot water products family.</h2><p>American Whirlpool and Vita Spa share the manufacturing heritage of MAAX Spas. That relationship gives both brands a common foundation in hot water product design, manufacturing experience and long-term ownership support while each brand keeps its own identity and product philosophy.</p></div><div class="heritage-mark">MAAX<br><small>SPAS</small></div></section>`}

brandPage=function(k){const x=brands[k],d=manufacturerDetails[k]||{headline:x.name,body:'Explore the collection in person.',points:x.features};return `<section class="brand-banner"><div class="brand-banner-inner"><span class="eyebrow">Hot Tub Factory Outlet</span><h1>${x.name}</h1><p>${d.headline}</p><div class="actions"><a class="btn primary" href="#chooser">Help Me Choose</a><a class="btn secondary" href="#spas">All Hot Tub Brands</a></div></div></section>${maaxBrands.has(k)?maaxHeritage():''}<section class="section"><div class="section-head brand-page-copy"><span class="eyebrow">About ${x.name}</span><h2>${d.body}</h2></div><div class="feature-grid">${d.points.map(f=>`<div class="feature"><h3>${f[0]}</h3><p>${f[1]}</p></div>`).join('')}</div></section><section class="section alt experience-strip"><div><span class="eyebrow">The part the internet cannot do</span><h2>Sit in the spa before you decide.</h2><p>Seat depth, jet placement, lounge fit and overall comfort feel different from person to person. We want the website to narrow your choices—not replace the showroom experience.</p></div><div class="actions"><a class="btn primary" href="#chooser">Use Spa Match</a></div></section>`};

brandCards=function(){return publicBrandOrder.map(k=>{const b=publicBrandCopy[k],d=manufacturerDetails[k];return `<a class="brand-card clean-brand" href="#brand/${k}"><div><h3>${b.name}</h3><span class="brand-tagline">${d?d.headline:b.tag}</span><p>${d?d.body:b.intro}</p></div><div class="arrow">→</div></a>`}).join('')};

const refinedHome=`<section class="hero refined-hero" id="home"><div class="hero-copy"><span class="eyebrow">Pittsburgh's Backyard Experts</span><h1>Make home your favorite place to be.</h1><p>Hot tubs, swim spas, pools, saunas and outdoor living—backed by more than 30 years of experience, two Pittsburgh-area showrooms and local service after the sale.</p><div class="actions"><a class="btn primary" href="#spas">Shop Hot Tubs</a><a class="btn secondary" href="#chooser">Help Me Choose a Spa</a></div></div><div class="hero-product"><div class="water-rings"></div><div class="hero-statement">RELAX<br><span>RECOVER</span><br>RECONNECT</div></div></section><section class="section"><div class="section-head"><span class="eyebrow">Start with the experience</span><h2>What do you want your backyard to do for you?</h2><p>Relax after work. Recover after a workout. Swim year-round. Entertain more. Build the backyard around how you actually want to live.</p></div><div class="category-grid refined-categories"><a class="category text-category" href="#spas"><h3>Hot Tubs</h3><span>Relax · Recover · Connect</span></a><a class="category text-category" href="#swim"><h3>Swim Spas</h3><span>Exercise · Therapy · Fun</span></a><a class="category text-category" href="#pools"><h3>Pools</h3><span>Make summer yours</span></a><a class="category text-category" href="#saunas"><h3>Saunas</h3><span>Heat · Wellness · Reset</span></a><a class="category text-category" href="#outdoor"><h3>Outdoor Living</h3><span>Cook · Gather · Stay outside</span></a></div></section><section class="section alt" id="spas"><div class="section-head"><span class="eyebrow">Hot Tub Brands</span><h2>Six brands. Six different ways to find the right fit.</h2><p>Explore each manufacturer in the order shown, or answer a few questions and let Spa Match narrow the showroom for you.</p></div><div class="brand-stack">${brandCards()}</div></section><section class="section"><div class="section-head"><span class="eyebrow">Why Hot Tub Factory Outlet</span><h2>Buying the spa is only the beginning.</h2></div><div class="why-grid"><div class="why">✓<strong>30+ years of experience</strong><p>Real-world guidance shaped by decades in the spa industry.</p></div><div class="why">✓<strong>Two Pittsburgh showrooms</strong><p>See, sit in and compare spas in Monroeville and Wexford.</p></div><div class="why">✓<strong>In-house service</strong><p>Local support from people who know the products we sell.</p></div><div class="why">✓<strong>Multiple quality brands</strong><p>Enough choice to fit the customer instead of forcing the customer to fit one brand.</p></div></div></section><section class="section dark chooser-callout"><span class="eyebrow">Not sure where to start?</span><div><h2>That is exactly what Spa Match is for.</h2><p>Tell us how you plan to use your hot tub and we’ll suggest a few brands to explore first.</p></div><a class="btn primary" href="#chooser">Start Spa Match</a></section>`;

route=function(){let h=location.hash.slice(1)||'home';if(h.startsWith('brand/'))document.querySelector('#app').innerHTML=brandPage(h.split('/')[1]);else if(h==='chooser')document.querySelector('#app').innerHTML=chooser;else if(generic[h])document.querySelector('#app').innerHTML=genericPage(h);else document.querySelector('#app').innerHTML=refinedHome;if(h==='chooser')renderQuiz();window.scrollTo(0,0)};route();