const API=(localStorage.getItem('htfoServiceApi')||'').replace(/\/$/,'')+'/api/service';
let token=sessionStorage.getItem('htfoServiceToken')||'',user=null,currentJob=null,currentInvoice=null;
const $=s=>document.querySelector(s),money=n=>Number(n||0).toLocaleString('en-US',{style:'currency',currency:'USD'}),esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
async function api(path,opts={}){const r=await fetch(API+path,{...opts,headers:{'Content-Type':'application/json',...(opts.headers||{}),...(token?{Authorization:`Bearer ${token}`}:{})}}),j=await r.json().catch(()=>({}));if(!r.ok){if(r.status===401)logout();throw new Error(j.error||`Request failed (${r.status})`)}return j}
function logout(){token='';user=null;sessionStorage.removeItem('htfoServiceToken');$('#app').hidden=true;$('#login').hidden=false}
function localYmd(d=new Date()){return `${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}-${String(d.getDate()).padStart(2,'0')}`}
function time(v){return v?new Date(v).toLocaleTimeString('en-US',{hour:'numeric',minute:'2-digit'}):'Unscheduled'}
function addr(w){return [w.street,w.street2,w.city,w.state,w.zip].filter(Boolean).join(', ')}
async function boot(){if(!token)return;try{const x=await api('/me');user=x.user;showApp()}catch{logout()}}
function showApp(){$('#login').hidden=true;$('#app').hidden=false;$('#who').textContent=user?.name||user?.username||'';$('#todayLabel').textContent=new Date().toLocaleDateString('en-US',{weekday:'long',month:'long',day:'numeric'});loadJobs()}
$('#loginForm').onsubmit=async e=>{e.preventDefault();$('#loginError').textContent='';try{const x=await api('/auth/login',{method:'POST',body:JSON.stringify({username:$('#username').value,password:$('#password').value})});token=x.token;user=x.user;sessionStorage.setItem('htfoServiceToken',token);showApp()}catch(err){$('#loginError').textContent=err.message}};
$('#logout').onclick=logout;$('#backJobs').onclick=()=>{$('#jobView').hidden=true;$('#jobsView').hidden=false;loadJobs()};$('#showAll').onchange=loadJobs;
async function loadJobs(){const rows=await api('/work-orders');const today=localYmd();let items=rows.filter(w=>w.scheduled_start&&localYmd(new Date(w.scheduled_start))===today);if(!$('#showAll').checked&&user?.name)items=items.filter(w=>String(w.assigned_to||'').toLowerCase()===String(user.name).toLowerCase());items.sort((a,b)=>new Date(a.scheduled_start)-new Date(b.scheduled_start));$('#jobs').innerHTML=items.map(w=>`<article class="job"><div class="row"><span class="pill">${esc(w.status)}</span><span class="muted">${esc(w.assigned_to||'Unassigned')}</span></div><h3>${time(w.scheduled_start)} · ${esc(w.customer_name||'Customer')}</h3><div>${esc(w.complaint||'Service call')}</div><div class="muted">${esc([w.city,w.state].filter(Boolean).join(', '))}</div><button class="primary" data-open="${w.id}">Open Job</button></article>`).join('')||'<div class="card"><b>No jobs shown.</b><p class="muted">Use “Show all techs” if you need to see the full dispatch schedule.</p></div>';document.querySelectorAll('[data-open]').forEach(b=>b.onclick=()=>openJob(b.dataset.open))}
async function openJob(id){const x=await api('/field/work-orders/'+id);currentJob=x.workOrder;currentInvoice=x.invoice;$('#jobsView').hidden=true;$('#jobView').hidden=false;renderJob(x)}
function renderJob(x){const w=x.workOrder,i=x.invoice,balance=i?Number(i.balance||0):0;$('#jobDetail').innerHTML=`<div class="panel"><div class="row"><span class="pill">${esc(w.status)}</span><span class="muted">${esc(w.work_order_number)}</span></div><h1>${esc(w.customer_name)}</h1><div><a href="tel:${esc(w.phone||'')}">${esc(w.phone||'No phone')}</a></div><div>${esc(addr(w))}</div><div class="muted">${esc([w.equipment_type,w.brand,w.model,w.serial_number&&('S/N '+w.serial_number)].filter(Boolean).join(' · '))}</div></div><div class="panel"><h2>Work</h2><label>Status<select id="fieldStatus"><option>scheduled</option><option>confirmed</option><option>en route</option><option>on site</option><option>awaiting parts</option><option>return visit needed</option><option>completed</option></select></label><label>Diagnosis<textarea id="fieldDiagnosis" rows="3">${esc(w.diagnosis||'')}</textarea></label><label>Work performed<textarea id="fieldWork" rows="3">${esc(w.work_performed||'')}</textarea></label><div class="grid2"><label>Labor hours<input id="fieldHours" type="number" min="0" step="0.25" value="${Number(w.labor_hours||0)}"></label><label>Parts used<input id="fieldParts" value="${esc(w.parts_used||'')}"></label></div><button id="saveFieldWork" class="primary">Save Job Update</button></div><div class="panel"><h2>Invoice</h2>${i?`<div class="money">${money(i.total_amount)}</div><div>Paid ${money(i.amount_paid)} · <b>${money(balance)} balance</b></div><div class="muted">${esc(i.invoice_number)} · ${esc(i.status)}</div>${x.payments.length?`<h3>Payments</h3>${x.payments.map(p=>`<div>${money(p.amount)} · ${esc(p.payment_method)}${p.reference_number?` #${esc(p.reference_number)}`:''}<span class="muted"> · ${esc(p.collected_by_name||'')}</span></div>`).join('')}`:''}${balance>0?'<div class="paybar"><button id="collectPayment" class="primary">Collect Payment</button></div>':'<p class="ok">PAID IN FULL</p>'}`:`<p>No invoice yet.</p><button id="createInvoice" class="primary">Create Invoice</button>`}</div>`;$('#fieldStatus').value=w.status||'scheduled';$('#saveFieldWork').onclick=saveWork;if($('#createInvoice'))$('#createInvoice').onclick=createInvoice;if($('#collectPayment'))$('#collectPayment').onclick=()=>openPayment(i)}
async function saveWork(){try{await api('/work-orders/'+currentJob.id,{method:'PATCH',body:JSON.stringify({status:$('#fieldStatus').value,diagnosis:$('#fieldDiagnosis').value,work_performed:$('#fieldWork').value,labor_hours:Number($('#fieldHours').value||0),parts_used:$('#fieldParts').value,labor_amount:Number(currentJob.labor_amount||0),parts_amount:Number(currentJob.parts_amount||0),trip_amount:Number(currentJob.trip_amount||0),tax_amount:Number(currentJob.tax_amount||0)})});await openJob(currentJob.id)}catch(e){alert(e.message)}}
async function createInvoice(){try{const i=await api(`/work-orders/${currentJob.id}/invoice`,{method:'POST'});currentInvoice=i;await openJob(currentJob.id)}catch(e){alert(e.message)}}
function openPayment(i){currentInvoice=i;const balance=Number(i.balance??(Number(i.total_amount)-Number(i.amount_paid)));$('#paymentInvoice').innerHTML=`<div class="money">${money(balance)}</div><div class="muted">${esc(i.invoice_number)} remaining balance</div>`;$('#payAmount').value=balance.toFixed(2);$('#payMethod').value='card';$('#checkNo').value='';$('#payNote').value='';toggleCheck();$('#paymentDialog').showModal()}
function toggleCheck(){$('#checkWrap').hidden=$('#payMethod').value!=='check';$('#submitPayment').textContent=$('#payMethod').value==='card'?'Open Secure Card Payment':'Record Payment'}$('#payMethod').onchange=toggleCheck;
$('#submitPayment').onclick=async e=>{e.preventDefault();const method=$('#payMethod').value,amount=Number($('#payAmount').value||0);if(amount<=0)return alert('Enter a payment amount.');try{if(method==='cash'||method==='check'){await api(`/invoices/${currentInvoice.id}/payments`,{method:'POST',body:JSON.stringify({payment_method:method,amount,reference_number:$('#checkNo').value,notes:$('#payNote').value})});$('#paymentDialog').close();await openJob(currentJob.id);return}const c=await api(`/invoices/${currentInvoice.id}/card-checkout`,{method:'POST',body:JSON.stringify({amount})});const f=document.createElement('form');f.method='POST';f.action=c.form_url;f.innerHTML=`<input type="hidden" name="token" value="${esc(c.token)}">`;document.body.appendChild(f);f.submit()}catch(err){alert(err.message)}};
boot();