const API=(localStorage.getItem('htfoServiceApi')||'').replace(/\/$/,'')+'/api/service';
let token=sessionStorage.getItem('htfoServiceToken')||'';
let activeCustomerId=null, workEquipmentRows=[];
const $=s=>document.querySelector(s), $$=s=>[...document.querySelectorAll(s)];
async function api(path,opts={}){const r=await fetch(API+path,{...opts,headers:{'Content-Type':'application/json',...(opts.headers||{}),...(token?{Authorization:`Bearer ${token}`}:{})}});const j=await r.json().catch(()=>({}));if(!r.ok){if(r.status===401) logout();throw new Error(j.error||`Request failed (${r.status})`)}return j}
function money(n){return Number(n||0).toLocaleString('en-US',{style:'currency',currency:'USD'})}
function dt(v){return v?new Date(v).toLocaleString():''}
function esc(v=''){return String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}
function customerName(c){return [c.first_name,c.last_name].filter(Boolean).join(' ')||c.company||'Unnamed customer'}
function showApp(user){$('#login').hidden=true;$('#app').hidden=false;$('#userName').textContent=user?.name||user?.username||'';showView('dashboard')}
function logout(){token='';sessionStorage.removeItem('htfoServiceToken');$('#app').hidden=true;$('#login').hidden=false}
async function boot(){if(!token)return;try{const x=await api('/me');showApp(x.user)}catch{logout()}}
function showView(id){$$('.view').forEach(v=>v.hidden=v.id!==id);if(id==='dashboard')loadDashboard();if(id==='customers')loadCustomers();if(id==='schedule'||id==='workorders')loadWorkOrders();if(id==='parts')loadParts();if(id==='orders')loadPartsQueue()}
$$('nav [data-view]').forEach(b=>b.onclick=()=>showView(b.dataset.view));$('#logout').onclick=logout;
$('#loginForm').onsubmit=async e=>{e.preventDefault();$('#loginError').textContent='';try{const x=await api('/auth/login',{method:'POST',body:JSON.stringify({username:$('#username').value,password:$('#password').value})});token=x.token;sessionStorage.setItem('htfoServiceToken',token);showApp(x.user)}catch(err){$('#loginError').textContent=err.message}};
const closeDialog=(id)=>{const d=document.getElementById(id);if(d?.open)d.close()};
const customerCancel=$('#customerForm .secondary');if(customerCancel)customerCancel.onclick=()=>closeDialog('customerDialog');
const equipmentCancel=$('#equipmentForm .secondary');if(equipmentCancel)equipmentCancel.onclick=()=>closeDialog('equipmentDialog');
const workCancel=$('#workForm .secondary');if(workCancel)workCancel.onclick=()=>closeDialog('workDialog');
async function loadDashboard(){const [d,w]=await Promise.all([api('/dashboard'),api('/work-orders')]);$('#statToday').textContent=d.today;$('#statOpen').textContent=d.open;$('#statCustomers').textContent=d.customers;$('#statUnpaid').textContent=money(d.unpaid);$('#upcoming').innerHTML=w.slice(0,12).map(workCard).join('')||'<p class="muted">No upcoming calls.</p>'}
function workCard(w){return `<div class="item"><div class="row between"><b>${esc(w.work_order_number)}</b><span class="pill">${esc(w.status)}</span></div><div>${esc(w.customer_name||'')} · ${esc(w.phone||'')}</div><div class="muted">${esc([w.equipment_type,w.brand,w.model].filter(Boolean).join(' ')||'No equipment selected')}${w.serial_number?` · S/N ${esc(w.serial_number)}`:''}</div><div><b>${dt(w.scheduled_start)}</b>${w.assigned_to?` · ${esc(w.assigned_to)}`:''}</div><div>${esc(w.complaint||'')}</div></div>`}
let searchTimer;$('#customerSearch').oninput=()=>{clearTimeout(searchTimer);searchTimer=setTimeout(loadCustomers,250)};
async function loadCustomers(){const rows=await api('/customers?q='+encodeURIComponent($('#customerSearch').value||''));$('#customerList').innerHTML=rows.map(c=>`<button class="item customer-row" data-id="${c.id}" style="text-align:left;color:inherit;background:white"><b>${esc(customerName(c))}</b><span>${esc(c.phone||'')} ${c.email?`· ${esc(c.email)}`:''}</span><span class="muted">${esc([c.street,c.city,c.state,c.zip].filter(Boolean).join(', '))}</span></button>`).join('')||'<p class="muted">No customers found.</p>';$$('.customer-row').forEach(b=>b.onclick=()=>loadCustomer(b.dataset.id))}
function productCard(e,history){return `<div class="equipment-card"><div class="row between wrap"><div><h3>${esc(e.equipment_type)} · ${esc([e.brand,e.model].filter(Boolean).join(' ')||'Model not recorded')}</h3><div class="muted">Serial: <b>${esc(e.serial_number||'—')}</b></div></div><button data-service-equipment="${e.id}">Create Service Call</button></div><div class="equipment-meta"><span>Installed/Purchased: ${esc(e.install_date||'—')}</span><span>Warranty through: ${esc(e.warranty_expires||'—')}</span>${e.location_notes?`<span>Location: ${esc(e.location_notes)}</span>`:''}</div>${e.notes?`<p>${esc(e.notes)}</p>`:''}<details><summary>Service history for this product (${history.length})</summary>${history.length?history.map(workCard).join(''):'<p class="muted">No service history for this product yet.</p>'}</details></div>`}
async function loadCustomer(id){activeCustomerId=String(id);const x=await api('/customers/'+id),c=x.customer;const unassigned=x.workOrders.filter(w=>!w.equipment_id);$('#customerDetail').innerHTML=`<div class="customer-toolbar row between wrap"><div><h2>${esc(customerName(c))}</h2><div>${esc(c.phone||'')} ${c.email?`· ${esc(c.email)}`:''}</div></div><div class="row wrap"><button class="secondary" id="addEquipmentBtn">+ Add Product</button><button id="customerServiceBtn">+ Create Service Call</button></div></div><div class="detail-grid"><div class="card"><h3>Customer Information</h3><p>${esc([c.street,c.street2,c.city,c.state,c.zip].filter(Boolean).join(', '))}</p>${c.notes?`<p>${esc(c.notes)}</p>`:''}<h3>Products / Equipment Owned</h3>${x.equipment.length?x.equipment.map(e=>productCard(e,x.workOrders.filter(w=>String(w.equipment_id)===String(e.id)))).join(''):'<p class="muted">No equipment recorded yet. Add the product once and its model, serial number and service history stay with this customer.</p>'}</div><div class="card"><h3>Complete Service History</h3>${x.workOrders.length?x.workOrders.map(workCard).join(''):'<p class="muted">No service calls yet.</p>'}${unassigned.length?`<p class="muted">${unassigned.length} service call(s) are not tied to a specific product.</p>`:''}<h3>Invoices</h3>${x.invoices.map(i=>`<div class="item"><b>${esc(i.invoice_number)}</b><span>${money(i.total_amount)} · ${esc(i.status)}</span><span class="muted">Paid ${money(i.amount_paid)} · Balance ${money(Number(i.total_amount)-Number(i.amount_paid))}</span></div>`).join('')||'<p class="muted">No invoices yet.</p>'}</div></div>`;$('#addEquipmentBtn').onclick=()=>openEquipmentDialog(id);$('#customerServiceBtn').onclick=()=>openWorkDialog(id,'');$$('[data-service-equipment]').forEach(b=>b.onclick=()=>openWorkDialog(id,b.dataset.serviceEquipment))}
$('#newCustomerBtn').onclick=()=>$('#customerDialog').showModal();$('#saveCustomer').onclick=async e=>{e.preventDefault();const b=Object.fromEntries(new FormData($('#customerForm')));const c=await api('/customers',{method:'POST',body:JSON.stringify(b)});$('#customerDialog').close();$('#customerForm').reset();await loadCustomers();await loadCustomer(c.id)};
function openEquipmentDialog(customerId){$('#equipmentForm').reset();$('#equipmentCustomerId').value=customerId;$('#equipmentDialog').showModal()}
$('#saveEquipment').onclick=async e=>{e.preventDefault();const b=Object.fromEntries(new FormData($('#equipmentForm')));if(!b.customer_id)return;await api('/equipment',{method:'POST',body:JSON.stringify(b)});$('#equipmentDialog').close();await loadCustomer(b.customer_id)};
async function loadWorkOrders(){const rows=await api('/work-orders');$('#scheduleList').innerHTML=rows.map(workCard).join('')||'<p class="muted">No scheduled calls.</p>';$('#workOrderList').innerHTML=rows.map(workCard).join('')||'<p class="muted">No work orders.</p>'}
async function populateWorkEquipment(customerId,selected=''){workEquipmentRows=[];$('#workEquipment').innerHTML='<option value="">No product selected / general service</option>';$('#selectedEquipmentSummary').textContent='';if(!customerId)return;const x=await api('/customers/'+customerId);workEquipmentRows=x.equipment;$('#workEquipment').innerHTML+=$xEquipmentOptions(workEquipmentRows);if(selected)$('#workEquipment').value=String(selected);renderSelectedEquipment()}
function $xEquipmentOptions(rows){return rows.map(e=>`<option value="${e.id}">${esc([e.equipment_type,e.brand,e.model].filter(Boolean).join(' '))}${e.serial_number?` · S/N ${esc(e.serial_number)}`:''}</option>`).join('')}
function renderSelectedEquipment(){const e=workEquipmentRows.find(x=>String(x.id)===String($('#workEquipment').value));$('#selectedEquipmentSummary').textContent=e?`${e.equipment_type} · ${[e.brand,e.model].filter(Boolean).join(' ')} · Serial ${e.serial_number||'not recorded'}${e.warranty_expires?' · Warranty through '+e.warranty_expires:''}`:'No specific product selected.'}
$('#workCustomer').onchange=()=>populateWorkEquipment($('#workCustomer').value,'');$('#workEquipment').onchange=renderSelectedEquipment;
async function openWorkDialog(customerId='',equipmentId=''){const customers=await api('/customers');$('#workForm').reset();$('#workCustomer').innerHTML='<option value="">Select customer…</option>'+customers.map(c=>`<option value="${c.id}">${esc(customerName(c)||c.email||c.phone)}</option>`).join('');if(customerId)$('#workCustomer').value=String(customerId);await populateWorkEquipment(customerId,equipmentId);$('#workDialog').showModal()}
$('#newWorkOrderBtn').onclick=()=>openWorkDialog();
$('#saveWork').onclick=async e=>{e.preventDefault();const b=Object.fromEntries(new FormData($('#workForm')));b.warranty=b.warranty==='true';b.equipment_id=b.equipment_id||null;await api('/work-orders',{method:'POST',body:JSON.stringify(b)});$('#workDialog').close();$('#workForm').reset();if(activeCustomerId&&String(b.customer_id)===activeCustomerId){showView('customers');await loadCustomer(activeCustomerId)}else loadWorkOrders()};
let partsTimer;$('#partsSearch').oninput=()=>{clearTimeout(partsTimer);partsTimer=setTimeout(loadParts,250)};
async function loadParts(){const q=$('#partsSearch').value||'';const rows=await api('/parts?q='+encodeURIComponent(q));$('#partsList').innerHTML=rows.map(p=>`<div class="item"><div class="row between"><div><b>${esc(p.description)}</b><div class="muted">${esc(p.brand||'')} ${p.category?`· ${esc(p.category)}`:''}</div></div><strong>${money(p.calculated_sell_price)}</strong></div><div>Supplier #: ${esc(p.supplier_part_number||'—')} · Mfg #: ${esc(p.manufacturer_part_number||'—')}</div><div class="muted">Supplier: ${esc(p.supplier||'—')} · Cost ${money(p.cost)}</div></div>`).join('')||'<p class="muted">No matching parts found.</p>'}
async function loadPartsQueue(){const rows=await api('/part-requests');$('#partsQueue').innerHTML=rows.map(r=>`<div class="item"><div class="row between"><b>${esc(r.work_order_number)} · ${esc(r.customer_name)}</b><span class="pill">${esc(r.status)}</span></div><div>${esc(r.description)}</div><div>Qty ${esc(r.requested_quantity)} · Supplier # ${esc(r.supplier_part_number||'—')} · Cost ${money(r.cost)}</div><div class="muted">Requested by ${esc(r.requested_by||'—')} ${r.manager_approved_by?`· Approved by ${esc(r.manager_approved_by)}`:''}</div>${r.status==='requested'?`<button data-approve="${r.id}">Manager Approve</button>`:''}${r.status==='approved'?`<div class="row"><input data-order-no="${r.id}" placeholder="Supplier order #"><button data-order="${r.id}">Mark Ordered</button></div>`:''}${r.status==='ordered'?`<button data-receive="${r.id}">Mark Received</button>`:''}</div>`).join('')||'<p class="muted">No part requests.</p>';$$('[data-approve]').forEach(b=>b.onclick=async()=>{try{await api(`/part-requests/${b.dataset.approve}/approve`,{method:'PATCH'});loadPartsQueue()}catch(e){alert(e.message)}});$$('[data-order]').forEach(b=>b.onclick=async()=>{try{const input=$(`[data-order-no="${b.dataset.order}"]`);await api(`/part-requests/${b.dataset.order}/order`,{method:'PATCH',body:JSON.stringify({supplier_order_number:input?.value||''})});loadPartsQueue()}catch(e){alert(e.message)}});$$('[data-receive]').forEach(b=>b.onclick=async()=>{try{await api(`/part-requests/${b.dataset.receive}/receive`,{method:'PATCH'});loadPartsQueue()}catch(e){alert(e.message)}})}
function parseCsv(text){const lines=text.replace(/\r/g,'').split('\n').filter(Boolean);if(!lines.length)return[];const split=line=>{let a=[],s='',q=false;for(let i=0;i<line.length;i++){const c=line[i];if(c==='"'){if(q&&line[i+1]==='"'){s+='"';i++}else q=!q}else if(c===','&&!q){a.push(s);s=''}else s+=c}a.push(s);return a};const headers=split(lines.shift()).map(h=>h.trim().toLowerCase());const key=h=>{if(/first.*name/.test(h))return'first_name';if(/last.*name/.test(h))return'last_name';if(/company/.test(h))return'company';if(/e-?mail/.test(h))return'email';if(/phone|mobile|cell/.test(h))return'phone';if(/address 2|street 2|apt|suite/.test(h))return'street2';if(/address|street/.test(h))return'street';if(/city/.test(h))return'city';if(/^state$|province/.test(h))return'state';if(/zip|postal/.test(h))return'zip';if(/note/.test(h))return'notes';return null};const map=headers.map(key);return lines.map(line=>{const vals=split(line),o={};map.forEach((k,i)=>{if(k&&!o[k])o[k]=vals[i]?.trim()||''});return o}).filter(o=>Object.values(o).some(Boolean))}
$('#importCsvBtn').onclick=async()=>{const f=$('#csvFile').files[0];if(!f)return $('#importResult').textContent='Choose a CSV file first.';try{const rows=parseCsv(await f.text());const x=await api('/customers/import',{method:'POST',body:JSON.stringify({rows})});$('#importResult').textContent=`Imported ${x.inserted} customer(s). Skipped ${x.skipped} likely duplicate(s). ${x.total} row(s) processed.`}catch(e){$('#importResult').textContent=e.message}};
boot();