const API=(localStorage.getItem('htfoServiceApi')||'').replace(/\/$/,'')+'/api/service';
let token=sessionStorage.getItem('htfoServiceToken')||'';
const $=s=>document.querySelector(s), $$=s=>[...document.querySelectorAll(s)];
async function api(path,opts={}){const r=await fetch(API+path,{...opts,headers:{'Content-Type':'application/json',...(opts.headers||{}),...(token?{Authorization:`Bearer ${token}`}:{})}});const j=await r.json().catch(()=>({}));if(!r.ok){if(r.status===401) logout();throw new Error(j.error||`Request failed (${r.status})`)}return j}
function money(n){return Number(n||0).toLocaleString('en-US',{style:'currency',currency:'USD'})}
function dt(v){return v?new Date(v).toLocaleString():''}
function esc(v=''){return String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}
function showApp(user){$('#login').hidden=true;$('#app').hidden=false;$('#userName').textContent=user?.name||user?.username||'';showView('dashboard')}
function logout(){token='';sessionStorage.removeItem('htfoServiceToken');$('#app').hidden=true;$('#login').hidden=false}
async function boot(){if(!token)return;try{const x=await api('/me');showApp(x.user)}catch{logout()}}
function showView(id){$$('.view').forEach(v=>v.hidden=v.id!==id);if(id==='dashboard')loadDashboard();if(id==='customers')loadCustomers();if(id==='schedule'||id==='workorders')loadWorkOrders(id)}
$$('nav [data-view]').forEach(b=>b.onclick=()=>showView(b.dataset.view));$('#logout').onclick=logout;
$('#loginForm').onsubmit=async e=>{e.preventDefault();$('#loginError').textContent='';try{const x=await api('/auth/login',{method:'POST',body:JSON.stringify({username:$('#username').value,password:$('#password').value})});token=x.token;sessionStorage.setItem('htfoServiceToken',token);showApp(x.user)}catch(err){$('#loginError').textContent=err.message}};
async function loadDashboard(){const [d,w]=await Promise.all([api('/dashboard'),api('/work-orders')]);$('#statToday').textContent=d.today;$('#statOpen').textContent=d.open;$('#statCustomers').textContent=d.customers;$('#statUnpaid').textContent=money(d.unpaid);$('#upcoming').innerHTML=w.slice(0,12).map(workCard).join('')||'<p class="muted">No upcoming calls.</p>'}
function workCard(w){return `<div class="item"><div class="row between"><b>${esc(w.work_order_number)}</b><span class="pill">${esc(w.status)}</span></div><div>${esc(w.customer_name||'')} · ${esc(w.phone||'')}</div><div class="muted">${esc(w.brand||'')} ${esc(w.model||'')} · ${esc(w.city||'')} ${esc(w.state||'')}</div><div><b>${dt(w.scheduled_start)}</b>${w.assigned_to?` · ${esc(w.assigned_to)}`:''}</div><div>${esc(w.complaint||'')}</div></div>`}
let searchTimer;$('#customerSearch').oninput=()=>{clearTimeout(searchTimer);searchTimer=setTimeout(loadCustomers,250)};
async function loadCustomers(){const rows=await api('/customers?q='+encodeURIComponent($('#customerSearch').value||''));$('#customerList').innerHTML=rows.map(c=>`<button class="item customer-row" data-id="${c.id}" style="text-align:left;color:inherit;background:white"><b>${esc([c.first_name,c.last_name].filter(Boolean).join(' ')||c.company||'Unnamed customer')}</b><span>${esc(c.phone||'')} ${c.email?`· ${esc(c.email)}`:''}</span><span class="muted">${esc([c.street,c.city,c.state,c.zip].filter(Boolean).join(', '))}</span></button>`).join('')||'<p class="muted">No customers found.</p>';$$('.customer-row').forEach(b=>b.onclick=()=>loadCustomer(b.dataset.id))}
async function loadCustomer(id){const x=await api('/customers/'+id),c=x.customer;$('#customerDetail').innerHTML=`<div class="detail-grid"><div class="card"><h2>${esc([c.first_name,c.last_name].filter(Boolean).join(' ')||c.company||'Customer')}</h2><p>${esc(c.phone||'')}<br>${esc(c.email||'')}</p><p>${esc([c.street,c.street2,c.city,c.state,c.zip].filter(Boolean).join(', '))}</p><p>${esc(c.notes||'')}</p><h3>Equipment</h3>${x.equipment.map(e=>`<div class="item"><b>${esc(e.equipment_type)} · ${esc(e.brand||'')} ${esc(e.model||'')}</b><span>Serial: ${esc(e.serial_number||'—')}</span></div>`).join('')||'<p class="muted">No equipment recorded yet.</p>'}</div><div class="card"><h3>Service History</h3>${x.workOrders.map(workCard).join('')||'<p class="muted">No service calls yet.</p>'}<h3>Invoices</h3>${x.invoices.map(i=>`<div class="item"><b>${esc(i.invoice_number)}</b><span>${money(i.total_amount)} · ${esc(i.status)}</span></div>`).join('')||'<p class="muted">No invoices yet.</p>'}</div></div>`}
$('#newCustomerBtn').onclick=()=>$('#customerDialog').showModal();$('#saveCustomer').onclick=async e=>{e.preventDefault();const b=Object.fromEntries(new FormData($('#customerForm')));await api('/customers',{method:'POST',body:JSON.stringify(b)});$('#customerDialog').close();$('#customerForm').reset();loadCustomers()};
async function loadWorkOrders(){const rows=await api('/work-orders');$('#scheduleList').innerHTML=rows.map(workCard).join('')||'<p class="muted">No scheduled calls.</p>';$('#workOrderList').innerHTML=rows.map(workCard).join('')||'<p class="muted">No work orders.</p>'}
$('#newWorkOrderBtn').onclick=async()=>{const customers=await api('/customers');$('#workCustomer').innerHTML='<option value="">Select customer…</option>'+customers.map(c=>`<option value="${c.id}">${esc([c.first_name,c.last_name].filter(Boolean).join(' ')||c.company||c.email||c.phone)}</option>`).join('');$('#workDialog').showModal()};
$('#saveWork').onclick=async e=>{e.preventDefault();const b=Object.fromEntries(new FormData($('#workForm')));b.warranty=b.warranty==='true';await api('/work-orders',{method:'POST',body:JSON.stringify(b)});$('#workDialog').close();$('#workForm').reset();loadWorkOrders()};
function parseCsv(text){const lines=text.replace(/\r/g,'').split('\n').filter(Boolean);if(!lines.length)return[];const split=line=>{let a=[],s='',q=false;for(let i=0;i<line.length;i++){const c=line[i];if(c==='"'){if(q&&line[i+1]==='"'){s+='"';i++}else q=!q}else if(c===','&&!q){a.push(s);s=''}else s+=c}a.push(s);return a};const headers=split(lines.shift()).map(h=>h.trim().toLowerCase());const key=h=>{if(/first.*name/.test(h))return'first_name';if(/last.*name/.test(h))return'last_name';if(/company/.test(h))return'company';if(/e-?mail/.test(h))return'email';if(/phone|mobile|cell/.test(h))return'phone';if(/address 2|street 2|apt|suite/.test(h))return'street2';if(/address|street/.test(h))return'street';if(/city/.test(h))return'city';if(/^state$|province/.test(h))return'state';if(/zip|postal/.test(h))return'zip';if(/note/.test(h))return'notes';return null};const map=headers.map(key);return lines.map(line=>{const vals=split(line),o={};map.forEach((k,i)=>{if(k&&!o[k])o[k]=vals[i]?.trim()||''});return o}).filter(o=>Object.values(o).some(Boolean))}
$('#importCsvBtn').onclick=async()=>{const f=$('#csvFile').files[0];if(!f)return $('#importResult').textContent='Choose a CSV file first.';try{const rows=parseCsv(await f.text());const x=await api('/customers/import',{method:'POST',body:JSON.stringify({rows})});$('#importResult').textContent=`Imported ${x.inserted} customer(s). Skipped ${x.skipped} likely duplicate(s). ${x.total} row(s) processed.`}catch(e){$('#importResult').textContent=e.message}};
boot();