(()=>{
const KEY='htfo_cart_v1',ATTR_KEY='htfo_employee_attribution_v1';
const money=n=>new Intl.NumberFormat('en-US',{style:'currency',currency:'USD'}).format(n);
const get=()=>{try{return JSON.parse(localStorage.getItem(KEY)||'[]')}catch{return[]}};
const getAttribution=()=>{try{const x=JSON.parse(localStorage.getItem(ATTR_KEY)||'null');return x&&x.valid?x:null}catch{return null}};
const setAttribution=a=>{if(a&&a.valid)localStorage.setItem(ATTR_KEY,JSON.stringify(a));else localStorage.removeItem(ATTR_KEY);window.dispatchEvent(new CustomEvent('htfo:attribution',{detail:getAttribution()}));return getAttribution()};
const save=c=>{localStorage.setItem(KEY,JSON.stringify(c));renderBadge()};
const add=p=>{const c=get();const hit=c.find(x=>x.id===p.id);if(hit)hit.qty+=1;else c.push({...p,qty:1,autoship:false,frequencyMonths:defaultFrequency(p)});save(c);toast(`${p.name} added to cart`)};
const parsePrice=t=>{const m=(t||'').replace(/,/g,'').match(/\$([0-9]+(?:\.[0-9]{1,2})?)/);return m?Number(m[1]):null};
const defaultFrequency=p=>/frog/i.test(`${p.name||''} ${p.sku||''}`)?4:/filter/i.test(`${p.name||''} ${p.sku||''}`)?12:3;
const discountRate=x=>x&&x.autoship?(getAttribution()?0.10:0.05):0;
const discountedPrice=x=>Number(x.price)*(1-discountRate(x));
function itemHtml(sku,name,price){return `<div class="item"><b>${name}</b><span>${sku}</span><em>This Week’s Sale Price</em><strong>${money(price)}</strong></div>`}
function cardHtml(sku,name,desc,price){return `<article class="card"><div class="body"><h3>${name}</h3><p>${desc}</p><div class="sku">${sku}</div><div class="sale">This Week’s Sale Price</div><div class="price">${money(price)}</div></div></article>`}
function frogCardHtml(sku,name,desc,price,imagePath){return `<article class="card frog-card"><div class="pic frog-pic"><img src="${imagePath}" alt="${name}" class="frog-product-photo"></div><div class="body"><h3>${name}</h3><p>${desc}</p><div class="sku">${sku}</div><div class="sale">This Week’s Sale Price</div><div class="price">${money(price)}</div></div></article>`}
function frogEaseFeatured(){if(document.getElementById('frog-ease'))return;const chemicals=document.getElementById('chemicals');if(!chemicals)return;const section=document.createElement('section');section.className='section alt frog-ease-featured';section.id='frog-ease';section.innerHTML=`<div class="wrap"><div class="head"><span class="eyebrow">Our preferred water-care program</span><h2>FROG @ease Water Care</h2><p>Our preferred easy-care system for hot tubs and swim spas. FROG @ease combines FROG Minerals with self-regulating SmartChlor technology for simpler routine water care and up to 75% less chlorine than standard hot-tub chlorine systems.</p></div><div class="grid">${frogCardHtml('01-14-3256','FROG @ease Floating System · Hot Tubs','Complete floating mineral + SmartChlor sanitizing system for hot tubs. Self-regulates and flips when the SmartChlor cartridge needs attention.',57.99,'assets/Frog Ease Hot Tub.jpg?v=20260901-6')}${frogCardHtml('01-14-3258','FROG @ease SmartChlor Refills · 3 Pack','Three replacement SmartChlor cartridges for the FROG @ease Floating System for hot tubs.',57.99,'assets/Frog Ease refills.jpg?v=20260901-6')}${frogCardHtml('FROG-SS-SYSTEM','FROG @ease Floating System · Swim Spas','Complete floating FROG @ease sanitizing system designed specifically for swim spas.',134.99,'assets/Frog Ease SS .webp?v=20260901-6')}${frogCardHtml('01-14-3284','FROG @ease SmartChlor Refill · Swim Spa','Single replacement SmartChlor cartridge for the FROG @ease Sanitizing System for Swim Spas.',46.99,'assets/Frog Ease SS refill.webp?v=20260901-6')}</div><div class="note"><strong>Auto-Ship & Save:</strong> choose Auto-Ship in your cart to save 5%. Customers enrolling with a valid HTFO employee code save 10% total on Auto-Ship purchases.</div></div>`;chemicals.parentNode.insertBefore(section,chemicals);const deptGrid=document.querySelector('.deptgrid');if(deptGrid&&!deptGrid.querySelector('a[href="#frog-ease"]')){const a=document.createElement('a');a.className='dept';a.href='#frog-ease';a.innerHTML='<small>Preferred water care</small>FROG @ease';deptGrid.insertBefore(a,deptGrid.firstChild);const old=deptGrid.querySelector('a[href="#chemicals"] small');if(old)old.textContent='Traditional water care'}}
function completeCatalog(){const chem=document.getElementById('chemgrid');if(chem&&!chem.textContent.includes('TSAC103'))chem.insertAdjacentHTML('beforeend',itemHtml('TSAC103','Total Hardness Test Strips',17.99)+itemHtml('TSAC104','TDS Test Strips',17.99));const acc=document.getElementById('accgrid');if(acc){const sediment=[...acc.querySelectorAll('.item')].find(x=>x.querySelector('span')?.textContent.trim()==='CHSE300');if(sediment){const name=sediment.querySelector('b'),price=sediment.querySelector('strong');if(name)name.textContent='Sediment Pre-Filter';if(price)price.textContent='$14.99'}if(!acc.textContent.includes('Sediment Filter'))acc.insertAdjacentHTML('beforeend',itemHtml('CHSE300','Sediment Filter',12.99))}const pdf=document.querySelector('img[src$=".pdf"]');if(pdf)pdf.closest('.pic')?.remove();const lifters=document.querySelector('#lifters .grid');if(lifters&&!lifters.textContent.includes('VSL400'))lifters.insertAdjacentHTML('beforeend',cardHtml('VSL400','VacuSeal 400 Cover Lifter','Premium VacuSeal-compatible cover lifter.',599)+cardHtml('VSLA201','VacuSeal 200 → 400 Conversion Kit','Conversion kit for compatible VacuSeal lifter systems.',249)+cardHtml('CLP100SS','Swim Spa ConvertALift','Powered cover-lifter solution for compatible swim spas.',2795)+cardHtml('CLP100SS-UG','Hot Tub → Swim Spa ConvertALift Upgrade','Upgrade package for compatible ConvertALift installations.',1299));const steps=document.querySelector('#steps .grid');if(steps&&!steps.textContent.includes('RADM036'))steps.insertAdjacentHTML('beforeend',cardHtml('RADM036','Deck-Mount Rail · up to 22 in','Compact deck-mount safety rail for lower spa installations.',189));const coverSkus={'Economy 4 × 2':'CVTH100','Bronze 4 × 2.5':'CVTH200','Silver 4 × 2.5':'CVTH300','Gold 5 × 3':'CVTH400','Platinum 6 × 4':'CVTH500'};document.querySelectorAll('#covers .card').forEach(c=>{const h=c.querySelector('h3');if(!h||!coverSkus[h.textContent.trim()]||c.querySelector('.sku'))return;const sku=document.createElement('div');sku.className='sku';sku.textContent=coverSkus[h.textContent.trim()];h.after(sku)})}
function productFrom(el){const name=(el.querySelector('h3,b')?.textContent||'').trim();const sku=(el.querySelector('.sku,span')?.textContent||name).trim();const price=parsePrice(el.querySelector('.price,strong')?.textContent);if(!name||price===null)return null;return{id:`${sku||name}|${name}`,name,sku,price}}
function buttonFor(el,p){if(el.querySelector('.add-cart'))return;const b=document.createElement('button');b.className='add-cart';b.type='button';b.textContent='Add to Cart';b.addEventListener('click',()=>add(p));const host=el.querySelector('.body')||el;host.appendChild(b)}
function decorate(){document.querySelectorAll('.card,.item').forEach(el=>{const p=productFrom(el);if(!p)return;if(p.name==='VacuSeal Covers')return;buttonFor(el,p)})}
function renderBadge(){const qty=get().reduce((s,x)=>s+x.qty,0);document.querySelectorAll('.cart-count').forEach(x=>x.textContent=qty)}
function chrome(){const a=document.createElement('a');a.href='cart.html';a.className='cart-fab';a.setAttribute('aria-label','View shopping cart');a.innerHTML='Cart <span class="cart-count">0</span>';document.body.appendChild(a);const s=document.createElement('style');s.textContent=`.add-cart{margin-top:14px;width:100%;border:0;border-radius:10px;background:#0b79b7;color:#fff;font-weight:900;padding:12px 14px;cursor:pointer;font-size:15px}.cart-fab{position:fixed;right:18px;bottom:18px;z-index:9999;background:#082642;color:white;text-decoration:none;border-radius:999px;padding:13px 17px;font-weight:900;box-shadow:0 8px 30px #0004}.cart-count{display:inline-grid;place-items:center;min-width:24px;height:24px;padding:0 6px;margin-left:5px;border-radius:999px;background:#f5b82e;color:#082642}.store-toast{position:fixed;left:50%;bottom:80px;transform:translateX(-50%);z-index:10000;background:#082642;color:#fff;border-radius:10px;padding:10px 15px;font-weight:800}.frog-ease-featured{border-top:4px solid #78b82a}.frog-pic{padding:14px;display:flex;align-items:center;justify-content:center;background:#fff}.frog-product-photo{display:block;width:100%;height:100%;object-fit:contain}`;document.head.appendChild(s)}
function toast(t){let x=document.querySelector('.store-toast');if(!x){x=document.createElement('div');x.className='store-toast';document.body.appendChild(x)}x.textContent=t;clearTimeout(x._t);x._t=setTimeout(()=>x.remove(),1500)}
document.addEventListener('DOMContentLoaded',()=>{chrome();frogEaseFeatured();completeCatalog();decorate();renderBadge()});window.HTFOCart={get,save,add,money,discountedPrice,discountRate,defaultFrequency,getAttribution,setAttribution};
})();